### ISSUE TITLE
複数曲の同時再生機能がほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#10]

**Comment by ryotayama** [comment]
https://twitter.com/7_dolphinsan/status/918037336868319232

**Comment by ryotayama** [comment]
https://twitter.com/7_dolphinsan/status/918037987975299072

**Comment by arigayas** [comment]
2017.10.11
https://twitter.com/7_dolphinsan/status/918037336868319232
ハヤえもんさんにはandroid版の開発に勤しんで欲しいけど参考になればと思いまたもや要望

・巷では聖徳太子の如く4曲同時再生できるアプリがあるそうです。4曲とは言わずに2曲同時再生機能が欲しい！AB保存で曲を切り取って貼ったりしてハヤえもんでマッシュアップとか作りたい！


2017.10.11
https://twitter.com/7_dolphinsan/status/918037987975299072
頭の中に「この曲とこの曲マッシュアップしたら絶対合う！」て思うのに難しいソフトいじれないですがハヤえもんならピッチ変更やエフェクト付け、曲保存が簡単なので検討願います！_:(´ཀ`」 ∠):

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
