### ISSUE TITLE
通常使うアプリのリストに入るようにしてほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#104]
参考URL
https://twitter.com/ryota_yama/status/953493984826961921

**Comment by aafxaa** [comment]
これ
https://github.com/ryotayama/Hayaemon_Android/issues/236
で出来るようになってる気がする。

（６）ファイラーアプリから音声ファイルを開く時の選択肢にハヤえもんが表示されるよう対応

ハヤえもんAndroid版、「リバーブ（カスタマイズ）」画面に「リセット」ボタンを追加した対応を含む、６点の対応を行ったver.2.03をリリース！（ハヤえもんAndroid版ver.2.03更新履歴）
http://hayaemon.jp/blog/archives/6765
