### ISSUE TITLE
未対応のファイル形式を再生するとクラッシュする。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#107]
https://twitter.com/4oki4DAN/status/959842522930470912
『もしかしてハヤえもんの泥版ってflac対応してない…？
wavとaacとmp3は問題なく再生できるけどflacはアプリが落ちる』

https://twitter.com/ryota_yama/status/959947105656647681
『flacまだ対応してません！　いずれ対応しますね٩( ᐛ )و』

https://twitter.com/arigayas/status/960067880879472642
『対応していないファイル形式でクラッシュしないようにしないと…。
出来れば「このファイル形式に対応していません」と表示されると尚良いと思います。』

**Comment by UmeboshiKantaro** [comment]
Androidリポジトリにお引越ししたため、closeします！(*･ω･)ﾉ
お引越し先⇒ https://github.com/ryotayama/Hayaemon_Android/issues/122
