### ISSUE TITLE
通知バーの背景色を白色から黒色に変更して欲しい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#113]
ゆっきーのAndroid版のバグ出しツイートから。
https://twitter.com/guxtuti_yukine/status/992775877883658240

確認した環境：
ハヤえもんのバージョンは1.47。
Androidのバージョンは8.0.0

**Comment by ryotayama** [comment]
ハヤえもんAndroid版ver.1.48で修正しました！
