### ISSUE TITLE
イコライザ：コントロール項目内の「.」が「_」になっている

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#124]
ゆっきーのAndroid版のバグ出しツイートから。
https://twitter.com/guxtuti_yukine/status/992775877883658240

確認した環境：
ハヤえもんのバージョンは1.47。
Androidのバージョンは8.0.0

**Comment by ryotayama** [comment]
ハヤえもんAndroid版ver.1.48で修正しました！
