### ISSUE TITLE
イヤホンの抜き差しで再生が停止しない。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#126]
ゆっきーさんのツイート: "イヤホン抜いても差しても再生止まらん( ˘ω˘ )"
https://twitter.com/guxtuti_yukine/status/992973479270993920

確認した環境：
ハヤえもんのバージョンは1.47。
Androidのバージョンは8.0.0

**Comment by ryotayama** [comment]
Hayaemon_Androidに移行したので、Closeします！
