### ISSUE TITLE
(Mac版β) メニューバーの位置がMacのその他アプリとはちょっと違う

### ISSUE THREAD

**Issue by mikuta0407** [ryotayama/Hayaemon#138]
Windowsに慣れてるので現状のほうが僕は好みではあるんですけども,

他のソフトと違って現在,メニューバー(上部のファイル,編集,表示とか)がアプリウィンドウ内に収められているのですが,Macの他のソフトは画面上部の時計とかリンゴマークとかのある場所に来ているので,純粋なMacユーザーさんが困惑するかも････?

**Comment by ryotayama** [comment]
macOS版のリポジトリに移行した事に伴いCloseします！
https://github.com/ryotayama/Hayaemon_macOS/issues/2
