### ISSUE TITLE
ウィジェット機能に対応してほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#14]

**Comment by UmeboshiKantaro** [comment]
これ、Androidのタグを追加かな？？

https://twitter.com/UmeboshiKantaro/status/950568704697237504
ハヤえもん
ウィジェット開発
いかがでしょう

https://twitter.com/UmeboshiKantaro/status/964650354691358720
(ウィジェットはAndroidでもありますしiPhoneでもありますよ〜
iPhoneのウィジェットは一番左のページ？みたいな所を指します
通知センターから右にスライドしたページのこと)

https://twitter.com/hekisu1/status/964719614109220864?s=21
僕はMusicaというアプリのウィジェットがお気に入りです笑

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
