### ISSUE TITLE
(Mac版β) 音楽ファイルをダブルクリックで開いたときの標準プレーヤーにできるようにしてほしい

### ISSUE THREAD

**Issue by mikuta0407** [ryotayama/Hayaemon#140]
Windows版では関連付けでできるのですが,Macではデフォルトではグレーアウトして通常使うアプリケーションに指定することができず,無理やり関連付けても起動後にファイルを再生してくれません.

**Comment by ryotayama** [comment]
macOS版のリポジトリに移行した事に伴いCloseします！
https://github.com/ryotayama/Hayaemon_macOS/issues/3
