### ISSUE TITLE
ショートカットキー（グローバルホットキー）の任意で設定する機能が欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#143]
https://twitter.com/kosequrage/status/994866202156683264
kosequrage さんのツイートから
『今回、ショートカットキー（グローバルホットキー）の任意設定機能は乗せてないでしょうか？』

使用バージョン：ハヤえもんMac版ver.0.01β1

**Comment by ryotayama** [comment]
macOS版のリポジトリに移行した事に伴いCloseします！
https://github.com/ryotayama/Hayaemon_macOS/issues/4
