### ISSUE TITLE
グローバルホットキーで操作出来る機能が欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#144]
https://twitter.com/kosequrage/status/994868982376263680
kosequrage さんからの要望ツイート
『テープ起こし用途だと、
テキスト入力している状態でプレーヤーをホットキー操作できる機能が必須なので、
Mac版でもグローバルホットキーの対応をぜひお願いしたいです。』

使用バージョン：ハヤえもんMac版ver.0.01β1

**Comment by ryotayama** [comment]
以下のissueと重複していた為、Closeします！
https://github.com/ryotayama/Hayaemon/issues/143
