### ISSUE TITLE
(Mac版β) デフォルトウィンドウサイズが大きい

### ISSUE THREAD

**Issue by mikuta0407** [ryotayama/Hayaemon#145]
12インチモデルですが,Windows版と違い,上下方向にはみ出るくらいの大きさで立ち上がってきます.
もうすこし小さめのサイズで起動してほしいです.
個人的には最小サイズくらいがちょうどいいのかなぁと思ってます.

**Comment by DaisukeAtaraxiA** [comment]
画面縦の解像度は何pixelでしょう？
試しに縦のコントロールの間隔を狭めてみました。
縦のサイズが640->540ピクセルくらいまでにはなります。
あとは、メニューをmacOSスタイルに合わせてメインウィンドウから外して少しかせぐくらいでしょうか。
<img width="935" alt="a" src="https://user-images.githubusercontent.com/5174793/40149294-dbab51e0-59ad-11e8-8943-95d00a77a96a.png">

**Comment by mikuta0407** [comment]
macbook12インチモデルですので、2,304 x 1,440ですが、おそらく倍表示なので実質縦は720くらいかと思われます。

**Comment by mikuta0407** [comment]
Retina対応後でも,大きかったです.

**Comment by ryotayama** [comment]
macOS版のリポジトリに移行した事に伴いCloseします！
https://github.com/ryotayama/Hayaemon_macOS/issues/5
