### ISSUE TITLE
「アップデートの確認」機能が動作しないのを修正してほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#151]
北島 健吾 🎸ハヤエモニックギタリスト
「ここからアプデ確認できるようにしたいでござる
まだわしの最新じゃないはずでござる」
https://twitter.com/kengo1228/status/995722697312161792

**Comment by arigayas** [comment]
macOS版のリポジトリに移行した事に伴いCloseします！
