### ISSUE TITLE
MacOS 10.9.5 でも動くようにして欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#155]
溝下 優也さんからのバグ報告
https://twitter.com/mizoshita_yuya/status/996612836263538688
『こんにちは！はじめまして。

macOS版が開発されたということで
早速ダウンロードしてみたのですが
起動するなり落ちてしまいました。

僕が使っているのはiMac 2012 late
OS は10.9.5なのですが
古いOS だと動かないということなのですかね？？』
![ddsufbxvaau5ntq](https://user-images.githubusercontent.com/11251874/40114507-29ebc350-5948-11e8-9016-7b5733108a20.jpg)

https://twitter.com/DaisukeAtraxia2/status/996673308669108225
Mac版開発者のDaisuke さんのコメント
『はじめまして。macOS版試してくれてありがとうございます！
りょーたさん、Qt5.10がサポートしていないバージョンだからかもしれないです。
Qt5.9を選んだのはLTSだからなんですけど、１つ古いLTSの5.6に落としても良いかもしれません。
5.6でも機能的に不足はないですから。』

https://twitter.com/ryota_yama/status/996687584204963841
良太さんのコメント
『なるほど！　Daisukeさんありがとうございます。
5.6に落としてやってみましょうか！
溝下さん、もし良かったらリリース前に動作確認にご協力いただけると
嬉しいのですが、いかがでしょう？？』

https://twitter.com/mizoshita_yuya/status/996687778548146176
溝下 優也さんからのコメント
『ぜひー！協力させてください』

**Comment by ryotayama** [comment]
@DaisukeAtaraxiA 
Daisukeさん、添付しまーす（一番上と一番下の部分）
他にも必要であれば、言ってくださいね。

<img width="1112" alt="2018-05-28 15 23 32" src="https://user-images.githubusercontent.com/6075785/40600219-91b3adee-628b-11e8-8930-602be9878f75.png">

<img width="1112" alt="2018-05-28 15 23 48" src="https://user-images.githubusercontent.com/6075785/40600230-9d339fe4-628b-11e8-9149-74b3e58fd34c.png">

**Comment by arigayas** [comment]
溝下 優也 @ mizoshita_yuya さんのツイート
https://twitter.com/mizoshita_yuya/status/1002547268770148353
『返信遅くなってすみません！
おかげさまで立ち上がりました！』

Closeで良いかな？

**Comment by DaisukeAtaraxiA** [comment]
はい、Closeで良いと思います。
