### ISSUE TITLE
コントロールタブに想定されていない値が入力されるとクラッシュする

### ISSUE THREAD

**Issue by ryutaro** [ryotayama/Hayaemon#158]
コントロールタブが文字フィールドなのでカット又はペーストで値を入力するとクラッシュしてしまう

現象及び再現手法
https://youtu.be/vURaM5xYBoc

**Comment by ryutaro** [comment]
再現手順は以下の通りです

フォームをロングタップ後表示されるメニューからカットをタップしフォームから離れるとクラッシュします

また、1000をペーストした場合もクラッシュしました

**Comment by ryotayama** [comment]
ハヤえもんiOS版ver.2.50でリリース予定です٩( ᐛ )و

**Comment by ryotayama** [comment]
ver.2.50で対応しました٩( ᐛ )و
