### ISSUE TITLE
A-Bループでレンジ外の値を設定すると正しく動作しない

### ISSUE THREAD

**Issue by ryutaro** [ryotayama/Hayaemon#161]
iOSアプリ版のA-Bループ設定で分は曲の時間によって制御されているが秒は常に59秒まであるため
ファイルの再生時間以上の値を指定すると正しく動作しなくなる

1. ファイル終了後次の曲に進まず頭出しが行われる
2. ファイル終了後次の曲に進まず停止する
(このときプレーヤーのコントロールアイコンは一時停止アイコンなので内部的には再生中？)

いずれの場合も再生リストから別の曲を選択するとB地点が初期化され復旧する

現象及び再現手法
https://youtu.be/I2NPIjc9kDA

**Comment by ryotayama** [comment]
ハヤえもんiOS版ver.2.50でリリース予定です٩( ᐛ )و

**Comment by ryotayama** [comment]
ver.2.50で対応しました٩( ᐛ )و
