### ISSUE TITLE
再生リスト画面の修正について

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#165]
https://twitter.com/umeboshikantaro/status/998380601588699137?s=21
iOS版の再生リスト画面にメニューボタンを増やしたら、ゴミゴミして見づらくなってしまったのでアイコン類を修正したい。
前バージョン⇒2.41

**Comment by ryutaro** [comment]
全てのファイルにアイコンをつけるとごちゃごちゃしちゃうので、ローカルにあるファイルにはアイコンをつけずに
クラウド上にあるファイルだけにアイコンを付けるというのはどうでしょうか？

**Comment by arigayas** [comment]
関連ある気がしたので #53 「iPhone機能追加：再生リストの画面」とリンクさせます

**Comment by arigayas** [comment]
変更前のスクリーンショット
![resized_01_ddr1a3ovaaevypr](https://user-images.githubusercontent.com/11251874/40321877-7689159c-5d6b-11e8-836d-30f0dac2c8e2.jpg)

変更案のスクリーンショット
![resized_02_ddr1a3rvwaavam4](https://user-images.githubusercontent.com/11251874/40321909-8f600e4a-5d6b-11e8-9c51-e67df2aec25b.jpg)

**Comment by arigayas** [comment]
うめぼし @UmeboshiKantaro
https://twitter.com/UmeboshiKantaro/status/998388431846756352
『あ、説明が不足してましたが、Dropbox マークはストリーミング再生が
わかるようにクラウドマークにしてみました。
将来的にGoogleドライブなんかに対応した時もこれでいけるかなと思います。
（Googleドライブ上のデータをストリーミング再生できるかはわからないけど笑）』

**Comment by ryotayama** [comment]
対応中です٩( ᐛ )و*
ryutaroさんから「クラウド上にあるファイルだけにアイコン」という案もありましたが、いったんローカルもアイコン表示する方向で対応してみて、ユーザーサイドからの反応を見てみる事にします。

**Comment by ryotayama** [comment]
ハヤえもんiOS版ver.2.43で対応済ー！٩( ᐛ )و
