### ISSUE TITLE
iOS版でDropboxのリンク解除ボタンが常に表示される

### ISSUE THREAD

**Issue by ryutaro** [ryotayama/Hayaemon#166]
動画撮影開始時点でDropboxとリンクしていない状態ですが、Dropboxのリンク解除が表示されており
リンクする事ができない(?)

そして、リンク解除を押しても再び開くとリンク解除ボタンが表示されている

現象及び再現手法
https://youtu.be/VpjhKssYOl8

**Comment by ryotayama** [comment]
ryutaroさん、わざわざ動画付きでありがとうございます！
そもそも未リンクなのに「Dropboxのリンクを解除」ってメニューが表示されてる事自体が分かりづらいですね！
デザイナーのうめちゃんと相談しつつ、改善を検討しまーす！

**Comment by arigayas** [comment]
うめさんのTwitter
https://twitter.com/UmeboshiKantaro/status/998764624265687040
『左上のメニューについて。
「追加」は再生リスト画面の「＋」ボタンと機能が被っているので消去でいいと思います。
「Dropboxのリンクを解除」はリンクしてない場合には非表示に。
「保存」と「再生中の曲をエクスポート」は再生リストの「…」メニューに入れられないでしょうか？？』
![resized_dropboxlink_ddxtinsvaaiojw_](https://user-images.githubusercontent.com/11251874/40343711-2866da6e-5dcc-11e8-970c-5cf54319365b.jpg)

良太さんのTwitterの返信
https://twitter.com/ryota_yama/status/998776418543648769
『おっけー！　保存とエクスポートだけは、再生中じゃなくてもできるようにする部分の作り込みがいるから
ちょっと時間がかかる見込み！！』

うめさんのTwitterの返信
https://twitter.com/UmeboshiKantaro/status/998780749175144448
『わかりました！！そしたらそっちは別でリリースしましょう👍』

「「追加」は再生リスト画面の「＋」ボタンと機能が被っているので消去でいいと思います。」の
参照画像は https://github.com/ryotayama/Hayaemon/issues/165#issuecomment-390732054

**Comment by ryotayama** [comment]
ver.2.55で対応しました₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
- Dropboxとリンクしていない時
![Image](https://i.imgur.com/qlGCown.jpg)
- Dropboxとリンクしている時
![Image](https://i.imgur.com/kDUH4YE.jpg)
