### ISSUE TITLE
再生リストの並び替えモードの画面修正

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#167]
https://twitter.com/umeboshikantaro/status/998350095035781120?s=21
https://twitter.com/umeboshikantaro/status/998482894996688896?s=21
再生リストの並び替えモードに入った時、アイコンがゴミゴミして見づらいので、「…」（メニュー）ボタンと「＋」（曲追加）ボタンを非表示にしたい。さらに再生リスト画面の下部に「並び替えを終了する」ボタンを配置したい。
前バージョン⇒2.41

**Comment by arigayas** [comment]
https://twitter.com/umeboshikantaro/status/998350095035781120
に貼られたスクリーンショット
![resized_01_ddrahg4v4aeqgd3](https://user-images.githubusercontent.com/11251874/40323055-3a7478cc-5d6f-11e8-8e4a-9101c7d8bc9c.jpg)

![resized_02_ddrahg5vqaan4nw](https://user-images.githubusercontent.com/11251874/40323063-435d2218-5d6f-11e8-9ac9-90e932783b5a.jpg)

![resized_03_ddrahg1u0amgfyw](https://user-images.githubusercontent.com/11251874/40323069-4896254a-5d6f-11e8-983b-daee08f20589.jpg)

![resized_04_ddrahg6v0aaig5k](https://user-images.githubusercontent.com/11251874/40323073-4c190d18-5d6f-11e8-8cb6-8deda05cd58f.jpg)

**Comment by arigayas** [comment]
#165 の画面を適用した画面案
https://twitter.com/umeboshikantaro/status/998482894996688896
![resized_05_ddts5wovqaafamn](https://user-images.githubusercontent.com/11251874/40323483-77179448-5d70-11e8-8ec8-8148e9d63696.jpg)

再生リスト画面の下部に「並び替えを終了する」ボタンを配置した画像
![resized_06_ddts5wkv0airi6i jpg orig](https://user-images.githubusercontent.com/11251874/40323507-8a195900-5d70-11e8-9486-56d345a75fe6.jpg)

**Comment by kengo1228** [comment]
「再生リスト内ではなくて、『リストそのものの左右を入れ替える』ってやつどうやったらいいの？
一番左が一等地のイメージだからそこに旬のものをおきたい。」

引用もと
https://twitter.com/kengo1228/status/1000917729023483904

引用もと
「再生リストを整理する」を押したら、うめちゃんのラフスケッチの左側の画面に遷移したいね！
https://twitter.com/ryota_yama/status/1000927795671846912

![dznmss2voaalmgk](https://user-images.githubusercontent.com/39563982/40594843-7bcc9b90-626c-11e8-9b9d-14088f03f761.jpg)

**Comment by ryotayama** [comment]
元々のissueについては、ver.2.44で対応しました٩( ᐛ )و

再生リスト自体の並び替えについては、別のissue #188 を立ち上げたので、このissueについてはクローズします。
