### ISSUE TITLE
「保存」を再生リストのメニューボタン内に移行する

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#169]
https://twitter.com/umeboshikantaro/status/998764624265687040?s=21
「保存」と「再生中の曲をエクスポート」は再生リストの「…」メニューに入れられないでしょうか？？
↓
https://twitter.com/ryota_yama/status/998776418543648769?s=21
おっけー！　保存とエクスポートだけは、再生中じゃなくてもできるようにする部分の作り込みがいるからちょっと時間がかかる見込み！！
↓
https://twitter.com/umeboshikantaro/status/998780749175144448?s=21
わかりました！！そしたらそっちは別でリリースしましょう👍

バージョン2.41

**Comment by arigayas** [comment]
行き違いで #166 のコメントと重複したので閉じますね。

**Comment by UmeboshiKantaro** [comment]
「保存」と「エクスポート」別々でissue登録した方がいいかな？？？？

**Comment by arigayas** [comment]
別けた方が良いですね

**Comment by arigayas** [comment]
GitHubのissueの運用をみんなで学習するためにReopenしました。

**Comment by UmeboshiKantaro** [comment]
こちらを「保存」にして「再生中の曲をエクスポート」を新規でissue登録しますね。
