### ISSUE TITLE
iOS版左上メニューの「追加」が重複しているので消去

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#170]
https://twitter.com/UmeboshiKantaro/status/998764624265687040
iOS版左上メニューの「追加」が再生リストの「＋」ボタンと機能が重複しているので消去する。

関連ツイート
https://twitter.com/UmeboshiKantaro/status/997323418201571329
ユーザーさん「エフェクトやイコライザの種類が増えたし、追加のボタンも2個あるしなあ、と個人的に思いました」
↓
https://twitter.com/UmeboshiKantaro/status/997324242877202432
うめぼし「メニューから追加するのと再生リストから追加するのと２つあるって意味かな？？
↓
https://twitter.com/UmeboshiKantaro/status/997324334329810944
ユーザーさん「あ、曲を追加するボタンです」

バージョン2.41

**Comment by ryotayama** [comment]
「追加」メニューを削除したバージョンをハヤえもんver.2.48としてリリース予定です٩( ᐛ )و

**Comment by ryotayama** [comment]
「追加」メニューを削除したバージョンをハヤえもんver.2.48としてリリースしました٩( ᐛ )و
