### ISSUE TITLE
逆位相に対応してほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#177]
◆使用しているOS：iOS版
◆使用しているバージョン：2.42

◆引用元
https://twitter.com/gakinohurennzu/status/981801851589832704

ども、
ハヤえもんはかなり使い易く、いつも使っているのですが、位相の反転が出来れば、もう神なので、出来たらお願いします。
(アップルストアでも言いましたが、ラグで送れたかわからないので。)

**Comment by ryutaro** [comment]
サンプル乗せておきます
イヤホンとかで聞いた方がわかりやすいと思います

[正位相](https://drive.google.com/open?id=18T8jObnZ-D9TCxsMyFozVj-gP8NCrIva)
[逆位相](https://drive.google.com/open?id=19pSBXCKUDpETVqa-jqwFvGJRkAH_ANvb)

位相空間が反転し、音の定位が破綻しているのが確認いただけます

**Comment by ryotayama** [comment]
ryutaroさん、めちゃくちゃ守備範囲広いですね！
今回のニーズとしては、ボーカルありとボーカル無しの音楽ファイルを持っている人が、ボーカルだけを抽出したいという用途との事でした！

**Comment by ryotayama** [comment]
対応しましたー！　次のバージョン（ver.2.45）で対応版をリリースします。
