### ISSUE TITLE
「再生中」状態のデザインをわかりやすくする

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#178]
https://twitter.com/UmeboshiKantaro/status/997036562377359361
うめぼし「「ステータス」や「状態」なのか「ボタン」なのかって問題は今後も度々訪れると思います。。 例えば、再生マークも上部は「再生するボタン」だけど、再生リストの方は「再生状態」かもしれない。これずっと違和感あるんすよね。。」
![ddyvne5u0aaa9dr](https://user-images.githubusercontent.com/32741225/40461220-355ba400-5f45-11e8-962d-bc6aa2c675e7.jpg)
↓
https://twitter.com/UmeboshiKantaro/status/997040728298569728
うめぼし「あくまで例示ですけど、画面上部のは「一時停止する」ボタン、曲名の横は「再生中」状態、という風にした方が見ててしっくりきますね。。何なら背景色変えてもいいと思いますφ(･ω･｡)」
![ddyzqcou8aau3tx](https://user-images.githubusercontent.com/32741225/40461224-3a5f3f3e-5f45-11e8-976a-b7f596bb1f29.jpg)

**Comment by arigayas** [comment]
@UmeboshiKantaro さんのツイート
https://twitter.com/UmeboshiKantaro/status/999498009485328387
『以前ラフスケッチしたものを貼っときますね！！もう少しブラッシュアップする必要はあります🙏』
#55 が関係するかな？

**Comment by UmeboshiKantaro** [comment]
iOS ver.2.49にて対応済みです
http://hayaemon.jp/blog/archives/5172

**旧「再生中」**↓
![img_7107](https://user-images.githubusercontent.com/32741225/42130264-a69e3af4-7d1a-11e8-92dc-6984a45046de.PNG)

**旧「一時停止中」**↓
![img_7108](https://user-images.githubusercontent.com/32741225/42130271-b95066ae-7d1a-11e8-9e18-7e0d4e2a1d18.PNG)

**新「再生中」**↓
![img_7109](https://user-images.githubusercontent.com/32741225/42130274-c111b924-7d1a-11e8-862e-61e1153366e3.PNG)

**新「一時停止中」**↓
![img_7110](https://user-images.githubusercontent.com/32741225/42130275-c8c0561c-7d1a-11e8-9ca7-eabda9092982.PNG)

**Comment by ryotayama** [comment]
わー、消し忘れ！　ありがとー₍₍ (ง*ᐛ)ว ⁾⁾
