### ISSUE TITLE
[再生中] 再生リストで曲名が長い場合、全て表示されないのでスクロールして欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#179]
https://twitter.com/UmeboshiKantaro/status/999560921876807680
『SEは狭いのですぐこうなります(*ﾉﾉ)
スクショはバージョン2.42』
![resized_se_2_42](https://user-images.githubusercontent.com/11251874/40472949-db97b14e-5f75-11e8-84b1-17811658020c.jpg)

曲名が長くなくてもスクロールした方が「再生中」だとわかりやすいかな？

**Comment by UmeboshiKantaro** [comment]
追加情報ですφ(･ω･｡)

https://twitter.com/ryota_yama/status/1028868398581669888?s=21

ふむふむ、iOSデフォルトのミュージックアプリだと一覧画面ではスクロールされないけど、再生中画面ではスクロールされる感じだった！
ちなみにiOSのデフォルトコントロールに自動スクロール機能は無いから、ライブラリを探すか、自前で作るかだね！

![Image](https://i.imgur.com/dPfFVrn.jpg)

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
