### ISSUE TITLE
スワイプ操作で曲を削除する機能を削除する

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#180]
スワイプ操作で曲を削除する機能はUIとしてわかりにくいだろうという意見から。

良太さんの解説
https://twitter.com/ryota_yama/status/999991493220646912
『ハヤえもんの再生リストに曲を追加する為の手段として、以下５つの種類があるのね。
①ミュージックライブラリから読み込む。
②Dropboxから読み込む。
③カメラロールから読み込む。
④他のアプリからエクスポート。
⑤録音する。

このうち、①はリンクだけ保持。
②→はウェブ上のDropboxにアクセス。
③〜⑤はハヤえもん内にファイルを持ってる。

で、削除をするときの挙動は③〜⑤については再生リスト上の曲を消すタイミングでファイルも削除してる。
①〜②は再生リスト上の曲を消すタイミングでリンクを持たなくなるだけ。』

**Comment by ryotayama** [comment]
関連issue: #181

**Comment by ryotayama** [comment]
これ賛否両論ありそうだけど、どーだろう？？

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
