### ISSUE TITLE
スワイプ操作で「プリセットを削除する」機能を削除する

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#181]
https://twitter.com/UmeboshiKantaro/status/1000001593889075200
『スワイプ削除機能、イコライザ画面にもありますよー。エフェクトにはないです！』

![resized_ dec4jbau0aa-jcp](https://user-images.githubusercontent.com/11251874/40549153-b3039480-6071-11e8-868a-2a19d3f23fe6.jpg)

**Comment by arigayas** [comment]
うめさんのTwitterでの続きのコメント。
https://twitter.com/UmeboshiKantaro/status/1000001593889075200
『そっちはまた別で考え直さないといけないからね。
再生リストの場合、「…」ボタンからも削除ができるけど、イコライザにはついてないの。
長押しメニューの「プリセットを整理する」から削除することはできるけど、
これも再生リスト画面と統一しないとわかりにくいよね。』
![resized_01_dec5yczvaaesn5o](https://user-images.githubusercontent.com/11251874/40550425-02fa9e7c-6075-11e8-9952-28baa27861bd.jpg)

![resized_02_dec5yczvaaaz670](https://user-images.githubusercontent.com/11251874/40550427-032f7bd8-6075-11e8-88d5-e66865096f43.jpg)


![resized_03_dec5yc-uqaazqzg](https://user-images.githubusercontent.com/11251874/40550424-02af33d8-6075-11e8-9d13-ef51a1278dc6.jpg)

**Comment by UmeboshiKantaro** [comment]
ありさんの２つ目のコメントを #191 として別issue登録しました

**Comment by arigayas** [comment]
issue検索で「エフェクト」という言葉があるissueに「エフェクト」ラベルを一括付与するのは良くないですね(汗)

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
