### ISSUE TITLE
エフェクトなどを設定した曲に表示される鍵アイコンが直感的にわかりにくいので別の物にして欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#183]
iOS版 ver.2.43
![dd9yp3kuqauz2qg](https://user-images.githubusercontent.com/11251874/40558870-aebceb4c-608f-11e8-9d6e-3de7c8c871a9.jpg)

例えば
![image](https://user-images.githubusercontent.com/11251874/40558887-bb78dbca-608f-11e8-9944-f417ab794d0d.png)
スパーク、パラメータ、ベル、ミュージック等のアイコンはいかがでしょうか？

**Comment by ryotayama** [comment]
「エフェクト」側ではなく、「ロックする」という動作側の挙動が直感的に分かった方がいいと思うので、却下とさせていただきます( ᐛ )ゞ
