### ISSUE TITLE
再生リストの曲名とアーティスト名が横幅より長い場合の省略位置を統一する

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#184]
https://twitter.com/umeboshikantaro/status/1000063759463796736?s=21
眠れない夜、試しにアーティスト名をめちゃくちゃ長くしてみた。ふむふむ。こういう表示になるのね。。
↓
https://twitter.com/umeboshikantaro/status/1000183967851544577?s=21
ちなみにタイトルをめちゃくちゃ長くした場合。切れるラインが違うんだよね。これ揃えたいなぁ。

iOSバージョン2.43

**Comment by UmeboshiKantaro** [comment]
https://twitter.com/ryota_yama/status/1000184595139067911?s=21
りょーたさんのコメント「ここかな？？」
↓
うめぼしのコメント「そうそこ！！！！」

**Comment by arigayas** [comment]
スクリーンショットを添付
![resized_defely0u0aawvoj](https://user-images.githubusercontent.com/11251874/40573322-d4d89662-60fa-11e8-8911-60597f7e799c.jpg)

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1000280418975825920?s=21

とりあえずこれ対応した！

![Image](https://i.imgur.com/XDHUJMQ.jpg)

**Comment by arigayas** [comment]
arigayasのコメント
https://twitter.com/arigayas/status/1000283096355225602
『鍵アイコンが無くても同じ位置で「...」になるのでしょうか？』

良太さんの返信コメント
https://twitter.com/ryota_yama/status/1000283320897294336
『イェス！！　鍵アイコンが無い時は動的に伸ばした方がいいなら
別イシューで対応するけど、うめちゃんはどー思う？？』

うめさんの返信コメント
https://twitter.com/UmeboshiKantaro/status/1000284357729312768
『動的に伸縮…！！ぜひホスィ…！！！！🙏』

**Comment by arigayas** [comment]
このissue 追加機能は#185 なのでこのissueは閉じます。
