### ISSUE TITLE
「曲順の並び替え」でスクロール時に錠マークが消滅する

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#186]
https://twitter.com/umeboshikantaro/status/1000604474530971648?s=21
再生リストの「曲順の並び替え」でスクロールすると錠マークが消滅する場合がある。

iOSバージョン2.44

**Comment by arigayas** [comment]
動画からスクリーンショットを撮りました。
![01](https://user-images.githubusercontent.com/11251874/40583333-804152d8-61c7-11e8-84ea-cc266a25454a.jpg)


↓リスト番号が変わってる
![02](https://user-images.githubusercontent.com/11251874/40583362-4bf982f6-61c8-11e8-87fb-fc03b1ebff91.jpg)

↓錠マークが消滅
![03](https://user-images.githubusercontent.com/11251874/40583363-50d6ddf0-61c8-11e8-9b1f-0fe977215301.jpg)

@UmeboshiKantaro 選んだ曲に錠マークがある場合どうなりますか？

**Comment by ryotayama** [comment]
修正しましたー！　次のバージョン（ver.2.45）で修正版をリリースします。
※鍵アイコンをメニューアイコンの幅分、右にスライドさせるメソッドが何度も呼び出された結果、ずれていたのが原因。 #187 と同じ原因。
