### ISSUE TITLE
Windows 版のバージョン情報にあるメールアドレスと Readme ファイルにあるメールアドレスが違う

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#19]
試したバージョン：Windows版 Ver 2.75 β4

Windows 版のバージョン情報にあるメールアドレス：edolfzoku.com

Readme ファイルにあるメールアドレス：gmail.com

**Comment by arigayas** [comment]
#12 バージョン情報関係

**Comment by ryotayama** [comment]
あ、これver.2.75β5で対応済でーす٩( ᐛ )و
