### ISSUE TITLE
ファイル保存時に空き容量不足のエラーメッセージを出す。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#190]
#189 関連のTwitterでのやりとり。

arigayasのコメント.
https://twitter.com/arigayas/status/1001382867895648256
『そういえば書き出す時にiPhoneの空き容量が足りなくなったときの処理って書いてあるのかな？
(ふと思った) もし(書き出すファイル形式に)WAVE形式追加するなら注意がいると思ったので。』

良太さんの返信
https://twitter.com/ryota_yama/status/1001385595719970816
『現状だと録音時に容量が足りない場合は、こんなエラーがでるけど、
保存時は出るようになってなかった。
WAVE対応のついでにエラー表示出すようにしておこうかな！』
![resized_error message_dewi43evwaawpl-](https://user-images.githubusercontent.com/11251874/40648912-8cdc5b4c-636a-11e8-88d8-6ed9ef09f635.jpg)

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
