### ISSUE TITLE
イコライザ画面を長押しメニューではなくボタンメニューに変更する

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#191]
https://twitter.com/umeboshikantaro/status/1000003393610371072?s=21
iOS版のイコライザ画面を、長押しによるメニューではなく「…」ボタンによるメニューに変更したい。
再生リスト画面と統一させた方が操作が分かりやすくなるため。

iOSバージョン:2.45

**Comment by ryotayama** [comment]
ver.2.52で対応しました٩( ᐛ )و
