### ISSUE TITLE
再生リストの「…」ボタンの範囲を拡張する

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#192]
再生リストの「…」ボタンをタップしようとした時に、再生もしくは一時停止されてしまうことがある。
「…」ボタンがこのような範囲になっていると推測します。（画像水色部分）

![b](https://user-images.githubusercontent.com/32741225/40665993-a83d8940-6399-11e8-941a-31afb566dae9.png)

↓

この範囲を拡張することで誤タップを防ぐことができます。（画像水色部分）

![a](https://user-images.githubusercontent.com/32741225/40666043-c5f3a87a-6399-11e8-8ca5-016ba7b07ec0.png)

iOSバージョン2.45

**Comment by ryotayama** [comment]
ver2.53で対応しました٩( ᐛ )و
