### ISSUE TITLE
最上部や最下部のコントローラー部分の背景の透過を無くして欲しい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#199]
良太さんのツイート：[ver.2.47の開発版スクリーンショット](https://twitter.com/ryota_yama/status/1002772833901002752)ですが
青枠で囲った部分が透けて見えるのは気になりだしたら、
![deqqkqcucaawtdp](https://user-images.githubusercontent.com/11251874/40877912-6a494cdc-66c3-11e8-92c0-6cd18b29e632.jpg)
ずっと気になる物なので 透過しないようにして欲しいです。

コントローラー部分は透けているけど広告部分は透けていないのもチグハグな印象を持ちますし。

**Comment by ryotayama** [comment]
ver.2.56で対応しました！
