### ISSUE TITLE
再生リストに追加しても一曲ずつ止まる機能が欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#200]
Shiho.S＠Fl_shiho さんの要望ツイート：
https://twitter.com/Fl_shiho/status/1002843827126693888
『わかる人にはわかる「ハヤえもん」さん、
いつもすごーくお世話になっています！
コンサート毎に再生リスト作ってあるのですが、
再生した時に通常モードでどんどん次の曲に進みますが、
**一曲ずつ止まる機能はどうやって設定すればいいんだろ？**
未対応かなぁ… #ハヤえもん』

良太さんの返信
https://twitter.com/ryota_yama/status/1002894845092900868
『未対応です！
現状だと１つの再生リストに１曲だけ入れておくって方法ぐらいですね。
いずれ対応しますね！』

**Comment by UmeboshiKantaro** [comment]
https://twitter.com/ryota_yama/status/988253594473324545?s=21
#ハヤえもんAppStoreでのやりとり
音楽プロデューサーです 素晴らしい ★★★★★
投稿者: 似顔絵島の村長 – 2018年4月16日
本当に素晴らしいまとまったソフト
僕も10年前まで音楽ソフト開発やっていましたが
かゆいところに手が届き素晴らしいですね
あと、プレーヤーソフトで案外無いのが
リストの
↓
https://twitter.com/ryota_yama/status/988253595719024641?s=21
1曲のみ再生。僕の知る限り見当たりません。
ライブで、iPhone音源流しが多くなって来ました。
でも、1曲終わった時、次の曲が流れてしまい困ります。
リピートなどはどのアプリも当たり前ですが
「1曲のみ再生」モードが付いたらもう完璧です！
検討ください！

これ、「1曲のみ再生」をつけるって話があったのですがissue未登録でしたっけ？

**Comment by arigayas** [comment]
これって**1曲をリピートする機能**って事なのでしょうか？

**Comment by UmeboshiKantaro** [comment]
リピートではなく選択した一曲が最後まで再生されたら停止または一時停止状態になる機能ですね。
再生終了時の状態については検討が必要だと思います。
こんな要望もありました。
↓
https://twitter.com/nigaoejima/statuses/988967242413965312
僕の勝手な思いですが 再生終わったら アクティブ行(反転)だけが下に行って止まるのがいいです

**Comment by ryotayama** [comment]
ハヤえもんiOS版ver.2.49にて対応しました٩( ᐛ )و
