### ISSUE TITLE
iOSの設定でフォントサイズを大きくした場合にハヤえもんのフォントサイズも連動して大きくしてほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#202]
◆使用しているOS：iOS版
◆使用しているバージョン：2.46

◆引用元
https://twitter.com/ryota_yama/status/1003195759842299904

iOS自体の設定でフォントサイズを変更していた場合でも画面が崩れない事を確認。ただ、フォントサイズを指定してしまっている都合上、大きな文字で表示されないという問題があるけど、これは別途検討。#あとでissue登録

**Comment by ryotayama** [comment]
iOSの設定でフォントサイズを最大にした時のスクリーンショットを添付します٩( ᐛ )و
![Image](https://i.imgur.com/jNOOnVW.jpg)
![Image](https://i.imgur.com/WYHLFtk.jpg)
![Image](https://i.imgur.com/ljD8HJ1.jpg)
![Image](https://i.imgur.com/Pgg1XGF.jpg)

**Comment by ryotayama** [comment]
文字を小さくした後に同じ画面のスクリーンショットを撮ったので添付。
![Image](https://i.imgur.com/8lM3Q2Z.jpg)
![Image](https://i.imgur.com/VrIWnHs.jpg)
![Image](https://i.imgur.com/zQ5M4J1.jpg)
![Image](https://i.imgur.com/f7BLl9I.jpg)

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
