### ISSUE TITLE
夜間モードが欲しい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#203]
きっかけは結（むすび）＠musubi8enishiさんのツイート
https://twitter.com/musubi8enishi/status/1003124885311242240
『ハヤえもん、いつか背景の色を変えられるようになると嬉しいなあ。』

良太さんの引用RTによる返信ツイート
https://twitter.com/ryota_yama/status/1003126547044110336
『夜間モードは付けようと思ってるけど、
何でもカスタマイズできるような方向性にはわりと慎重な姿勢かな！』

**Comment by ryotayama** [comment]
https://twitter.com/muchi_shumi/status/1025555132786728960

機能追加の要望です!
Twitterのようにナイトモード?ダークモード?を追加してほしいです!

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
