### ISSUE TITLE
プリセットの項目を並べ替えようとするとアプリが強制終了してしまう

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#204]
adako＠Sound0fHydrogenさんのツイート
https://twitter.com/Sound0fHydrogen/status/1003235711464529920
『リプライありがとうございます。
突然のお願いで恐縮ですが、iPhoneのハヤえもんアプリにて、
プリセットの項目を並べ替えようとするとアプリが強制終了してしまう事があるので、
修正して頂けると幸いです。
突然の長文失礼しました。』

良太さんの返信ツイート
https://twitter.com/ryota_yama/status/1003236334553559041
『ありがとうございます！
以前から同様の報告を頂いてるんですが、
こちらこ環境で再現できておらず修正までいたっておりません。
もう少し色々試してみますね！』

**Comment by arigayas** [comment]
再現手順っぽいツイートをしていた鍵アカウントのサキュバスさんからの情報です。
現時点での再現手法

1. アプリを開き
2. イコライザ画面を表示し項目をロングタップの上
3. プリセットを整理するをタップ後
4. ハンバーガーボタンをタップアンドホールドしバイブレーションがなった時点
5. 以降任意のタイミング任意の場所でリリースするとクラッシュする

(この時項目を移動したかに関わらない)

動画の中では2回強制終了してます。
https://twitter.com/arigayas/status/1004308264421429248

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
