### ISSUE TITLE
再生リスト名の最大文字数を制限する

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#205]
再生リスト名の最大文字数が制限されていないため、制限を設ける。
最大40字が適切？

**Comment by arigayas** [comment]
今日はver.2.47で更新予定の再生リストの機能改善作業をしていた良太さんのスクリーンショットツイート
https://twitter.com/ryota_yama/status/1003232084289187840
![resized_longplaylistname_dewyqhav4aa3057](https://user-images.githubusercontent.com/11251874/40887162-1e062c48-677f-11e8-9a2c-039377c27e91.jpg)

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
