### ISSUE TITLE
音程のスピンボックスへキーボードで数値を入力した時の動作が正しくない

### ISSUE THREAD

**Issue by DaisukeAtaraxiA** [ryotayama/Hayaemon#206]
音程のスピンボックスにキーボードで値を入力した時、2つ目に入力した値が1つ目に入力した値と逆になることがある。以下の手順で再現する:
1. 音程のスピンボックスにフォーカス(テキストが全て選択状態)
2. 12と入力
スピンボックスのテキストは#21となる。

**Comment by arigayas** [comment]
macOS版のリポジトリに移行した事に伴いCloseします
ryotayama/Hayaemon_macOS/issues/17
