### ISSUE TITLE
再生リスト一覧画面のボタン表示が乱れている

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#207]
https://twitter.com/umeboshikantaro/status/1003569617132851200?s=21
新しく追加された再生リスト一覧画面にて、「…」ボタンの表示が乱れているのを修正する

iOSバージョン2.47

**Comment by arigayas** [comment]
うめさんのTwitterのスクリーンショットに赤丸で囲った物を添付します。
![ver247_de1lpiovmaazqmv](https://user-images.githubusercontent.com/11251874/40910370-e87b7904-6826-11e8-9776-4f97d1b58abc.jpg)

**Comment by UmeboshiKantaro** [comment]
これ関係ありますかね？？

https://twitter.com/ryota_yama/statuses/1003091329730007040
これ、同じ位置を指定してるのに再描画すると直るからiOSのバグかもしれないと思い始めたけど、とりあえず無駄に２回描画すれば正しい位置になるからいったんその方法でしのぐ事にした。

**Comment by arigayas** [comment]
端から見ると関係ありそう。

**Comment by ryotayama** [comment]
ハヤえもんiOS版ver.2.50でリリース予定です٩( ᐛ )و

**Comment by ryotayama** [comment]
ver.2.50で対応しました٩( ᐛ )و
