### ISSUE TITLE
Windows版Readme ファイルにある坂口くんのTwitterIDが削除されて無効になっている

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#208]
ご本人に確認する必要がありますが
坂口くん（Twitter: @guxtuti_cording）つまり、現在良太さんやうめさんには、ゆっきーと呼ばれている方のTwitterIDを更新する必要がある。

Version 2.75 β 5 開発版

**Comment by YukineKazuha** [comment]
このアカウントで今後行くとははっきり言えない状態で更新したとしても、この先またアカウントが変わるかもしれない。
更に、ユーザーサポートも出来ない･コードは一文字程度しか変えていない。
そんな状態ならば明記せずにそのIDの部分を削除した方が良いのではないかと思います。

**Comment by ryotayama** [comment]
対応しました٩( ᐛ )و
