### ISSUE TITLE
不具合報告のリンクから遷移するツイート画面で各種情報が自動で補完されるようにしてほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#209]
◆使用しているOS：iOS版
◆使用しているバージョン：2.47

◆引用元
https://twitter.com/ryota_yama/status/1003954614012600320

いったん出せるものは出してみたけど、もはや「ハヤえもんについて」じゃなくてユーザー側の情報を出してる。

とはいえ、ユーザーサポートするのにOSとか機種名があったらプラスになる。

これを解決するには、「ハヤえもんについて」画面にはハヤえもんの情報のみを出して、メニュー→不具合報告・機能→→要望が選ばれた時にツイート画面にハヤえもんのバージョン情報とユーザー側のOS／端末情報をツイート内容に含めるようにするのがいいんじゃないかと思うけどどうだろう？

もしこれで良ければ、いったん「ハヤえもんについて」画面には、バージョン: 2.47だけ出すようにして、不具合報告・機能要望→→に必要な情報を含めるようにするのは別issueで対応しよーかな！ #長い
うめちゃん、余裕のある時に意見ちょーだい @UmeboshiKantaro

![de7dyxyu0aa2nka](https://user-images.githubusercontent.com/6075785/40977093-f35f10c6-690a-11e8-9a03-954ccf7da06a.jpg)

https://twitter.com/UmeboshiKantaro/status/1003956945764532224
わー！ありがとうございます！！
確かに！この画面にはハヤえもんのバージョンのみにしましょう！
そんで「不具合報告・機能要望」メニューから

@ryota_yama ハヤえもん ver.2.47
端末情報：
iOS：

って感じで新規ツイート生成して、ユーザーサポートに繋げられると素敵っすね…！👍

https://twitter.com/arigayas/status/1003957187247419392

素敵！！ @ryota_yama

◆補足情報
#76 の対応中にでてきた改善点

**Comment by ryotayama** [comment]
◆メモ書き
≪OS名取得≫
NSProcessInfo.processInfo.operatingSystemVersionString
≪機種名取得≫　※「#include <sys/sysctl.h>」必要
size_t size;
sysctlbyname("hw.machine", NULL, &size, NULL, 0);
char *machine = malloc(size);
sysctlbyname("hw.machine", machine, &size, NULL, 0);
NSString *deviceName = [NSString stringWithCString:machine encoding:NSUTF8StringEncoding];
free(machine);

**Comment by ryotayama** [comment]
◆メモ書き
Twitter Kit SDKのサポート終了のお知らせ
https://blog.twitter.com/developer/ja_jp/topics/community/2018/TKSDK_tr.html

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
