### ISSUE TITLE
入力したテキストを一気に消す為の「×」ボタンがほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#210]
◆使用しているOS：iOS版
◆使用しているバージョン：2.47

◆引用元
https://twitter.com/satoupawapuro12/status/1003987305131008002

こんばんは！
iOS版のハヤえもんについて要望です。
アーティスト名などを変更する際、写真のようなテキスト全部消しのバツボタンをつけてほしいです。
些細なことですが、よろしくお願いします。

**Comment by ryotayama** [comment]
対応しました。ver.2.60でリリース予定です٩( ᐛ )و

**Comment by ryotayama** [comment]
こんな感じ₍₍ (ง*ᐛ)ว ⁾⁾
![Image](https://i.imgur.com/GNohd7Z.jpg)

**Comment by arigayas** [comment]
おお！Webサイトとかで見るやつだ！
