### ISSUE TITLE
「次に再生」機能がほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#216]
◆使用しているOS：iOS版
◆使用しているバージョン：2.48

◆引用元
https://twitter.com/ryota_yama/status/1004899404099096576

#ハヤえもんAppStoreでのやりとり
そまるん ★★★★★
投稿者: なんてね。。 – 2018年6月6日
曲選択ビューの右側にあるメニューに「次に再生」機能がほしい

デベロッパの回答 – 2018年6月8日
はじめまして！　ハヤえもん開発者のりょーたと申します٩( ᐛ )و
「次に再生」いいですよね！　検討してみます！
ツイッター（@ryota_yama）上でも、開発過程の発信やユーザーサポートを行なっていますので、もし良かったら覗いてみてくださいませ。

**Comment by ryotayama** [comment]
https://twitter.com/UmeboshiKantaro/status/1004904706148200448

うめぼし
返信先: @ryota_yamaさん
ありがとうございます！！これ私もほしいと思ってたー！！🙏✨✨

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1004905139004588032

りょーた
返信先: @UmeboshiKantaroさん
これちょっと挙動を整理する必要があるね。
□「次に再生」メニューはどこに付けるか。
□「次に再生」を選んだ後、また別の曲の「次に再生」を選んだらどう挙動するか。

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
