### ISSUE TITLE
画面下部のタブメニューのデザインをリニューアルする

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#217]
画面下部の「再生リスト」や「コントロール」などのタブメニューを、#214 に合わせてデザインのリニューアルをはさみたいと思います。(*･ω･)ﾉ

**Comment by arigayas** [comment]
デザインのリニューアル前のスクリーンショットが記録として欲しいです。

**Comment by arigayas** [comment]
良太さんの[スクリーンショットツイート](https://twitter.com/ryota_yama/status/1008165011624083457)から切り抜きました。
### Ver. 2.50 スクリーンショット
![bottomcontroller_v250](https://user-images.githubusercontent.com/11251874/41506328-8e835e8c-7256-11e8-9d01-fba4e676c54f.png)

**Comment by arigayas** [comment]
関連するissue：#199

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
