### ISSUE TITLE
メニューを左からスライドするメニューにしてほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#220]
◆使用しているOS：iOS版
◆使用しているバージョン：2.48

現状の下から出てくるメニューだとiPhone SEなどの画面が小さい端末だと、画面に表示されるメニュー数に限りがあり、操作性が悪い為、左からスライドするメニューにしてほしい。

**Comment by UmeboshiKantaro** [comment]
現行のメニュー項目↓

* 曲を追加
* Dropboxのリンクを解除
* 不具合報告・機能要望
* レビュー投稿
* 広告を非表示にする
* ハヤえもんについて

追加メニュー案↓

* 再生中の曲を保存／エクスポート

（コントロールやABループなど、再生リスト以外の画面を表示している間でも保存することができる）

* なうぷれ

（再生中の曲をツイッターなどにシェアできる機能。Now playing）

* ユーザー情報

（人物アイコン。ユーザー名を登録して録音の保存時にアーティスト名として入れておける。ツイッターやフェイスブックを登録してシェアすることができる等）

* 設定

（歯車アイコン。夜間モードをはじめとするカラーテーマの選択や、コントロールの小数点以下の設定を保存しておける機能）

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
