### ISSUE TITLE
iOS版 の更新履歴一覧が欲しい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#221]
更新頻度が高いので早めに作らないと作業が徐々に大変になっていくと思います。

上部が新しい物になるように記述する。
_しかしこの作業やるとなると、作業漏れが起こりそうで怖いなぁ_

# 作例 

## Ver. 2.49  2018/6/10  

- 再生モードに「１曲のみ」というモードを追加
- 上部のコントロールアイコンリニューアル
- 再生リストのアイコン表示をリニューアル

## Ver. 2.48 2018/6/7

- メニューに「ハヤえもんについて」というメニューを追加
- 「追加」メニューを削除

**Comment by arigayas** [comment]
関連するissue：#222 #223

更新(リリース)した日付もあった方が良いかもですね。

**Comment by ryotayama** [comment]
移行済の為、Closeします！
