### ISSUE TITLE
iTunesのファイル共有機能に対応してほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#224]
◆使用しているOS：iOS版
◆使用しているバージョン：2.49

◆引用元
https://twitter.com/ryota_yama/status/1005648897195118593
#ハヤえもんAppStoreでのやりとり
良い ★★★★☆
投稿者: k.h12125 – 2018年6月5日
音楽の音程、速さなどを自由に変えることができて大変便利です。カラオケの練習などに重宝しています。

<個人的な要望>
- iPhoneとPCを繋いでいる際に、 iTunesのファイル共有をハヤえもんでもできるようにして欲しいです。ハヤえもんのファイル内にある音楽ファイルをPCへ保存、またはPCからハヤえもんのファイルに音楽ファイルの追加をできるようにして頂けるとありがたいです。

<個人的な提案>
- "メニュー"は右側にある「・・・」で表示できるので、曲を長押しで"メニュー"を表示するのでは無く、iPhoneのホーム画面のアプリアイコンのように、長押ししながら曲の移動(曲順の並び替え)をできるようにすれば便利になるのではないでしょうか。
長押しが分からない方にも今までどおり、メニューから曲順の並び替えができるようにする形で。

長文失礼しました。
ご検討頂ければ幸いです。

デベロッパの回答 – 2018年6月10日
k.h12125さん、ありがとうございます！
りょーたです٩( ᐛ )و
ファイル共有に対応するべく調査してみますので、しばらくお待ちくださいね！
メニューについては、「・・・」メニューでできるようになりましたので、長押しに別の意味を持たせるのも確かにアリですね！
ちょっと考えてみます。
また何かありましたら、いつでも何でもご連絡くださいね。
ツイッター（@ryota_yama）でもサポートを行なっていますので、もし良かったら覗いてみてくださいませ。

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
