### ISSUE TITLE
複数曲の削除、移動に対応してほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#226]
◆使用しているOS：iOS版
◆使用しているバージョン：2.49

◆引用元
https://twitter.com/alxd_dororin5/status/1005737077411962880

iTunesの編集機能みたいに曲を複数選択して、まとめて削除や移動できるように私はしてほしい。

**Comment by UmeboshiKantaro** [comment]
曲名の長押しによってチェックボックスが表示される仕組みを採用できないか、画面を考えています(*･ω･)ﾉ

現在、Googleフォトがそのような仕様になっています。

↓長押し前の状態
![img_8197](https://user-images.githubusercontent.com/32741225/42415863-47c4a8f4-8299-11e8-9849-d0e9f8753a6d.PNG)

↓長押し後の状態
![img_8198](https://user-images.githubusercontent.com/32741225/42415867-674859d2-8299-11e8-82a2-a121dcd345be.PNG)

参考まで(*･ω･)ﾉ

**Comment by ryotayama** [comment]
いいね！　Googleフォトの操作性好き！

**Comment by UmeboshiKantaro** [comment]
複数選択ができるようになると、
「２曲同時再生機能が欲しい」 #296 
にも対応できるかもしれないので、それも踏まえながら検討してみますね(*･ω･)ﾉ

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
