### ISSUE TITLE
iCloud Driveからハヤえもんへの複数曲のエクスポートに対応してほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#227]
◆使用しているOS：iOS版
◆使用しているバージョン：2.49

◆引用元
https://twitter.com/al9hodo/status/1002727053089624064

ボイトレCDを片っ端からハヤえもんに取り込む作業。

だがなぜか、iCloudDriveからの読み込みが1曲ずつしかできない……

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
