### ISSUE TITLE
コントロール画面のX軸とY軸を「♯」「♭」「速」「遅」ボタンと重ならないようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#229]
◆使用しているOS：iOS版
◆使用しているバージョン：2.49

◆引用元
https://twitter.com/UmeboshiKantaro/status/886977240507981824

えーと、コントロール画面のX軸とY軸が文字とカブってるのがずっと気になってました！ ♯♭速遅の文字部分をタップするごとに1目盛ずつ移動できたり、長押しでスライドするのも分かりにくくてもったいないなと…！ざっくりですが3枚目みたいにグラフと文字が分かれてると良いなと思います！

**Comment by arigayas** [comment]
https://twitter.com/UmeboshiKantaro/status/886977240507981824
でツイートしたのが2017年7月18日なので画面は古いスクリーンショットです。

当時時点のスクリーンショット
![resized_01_de8tgi-u0aaft6p](https://user-images.githubusercontent.com/11251874/41211024-eaa84448-6d6f-11e8-973d-78d05618c589.jpg)


うめさんの改善案
![resized_03_de8tgi4vyaablmq](https://user-images.githubusercontent.com/11251874/41211043-0024a91a-6d70-11e8-8476-731a80e1d8c0.jpg)

**Comment by arigayas** [comment]
ハヤえもんiOS版ver.2.51 にて対応しました
