### ISSUE TITLE
出力デバイスを選択できるようにしてほしい(自動的にアクティブな再生デバイスに切り替って欲しい)

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#23]

**Comment by arigayas** [comment]
試したバージョン：Windows版 Ver 2.75 β4 + Windows 10

現状だと聞々ハヤえもんが起動した時に「既定のデバイス」に設定された「出力デバイス」から音声が出るようになっていますね。

起動してから「既定のデバイス」を切り替えて音声ファイルを再生しても「出力デバイス」が変わらないですね。


![image](https://user-images.githubusercontent.com/11251874/31660539-b2016442-b372-11e7-871e-45a7b1ab0ba3.png)

**Comment by mikuta0407** [comment]
起動後に既定のデバイスを変えても変わらないのは､iTunesとかも同じ挙動しますね｡

**Comment by arigayas** [comment]
自動的に変わるようにして欲しいという主旨のツイートをいただいた。
https://twitter.com/pre387/status/954545034790973440
『この場合ヘッドホンから音声出力を行うには「ヘッドホンを接続→ハヤえもん起動→再生」の手順を踏まなくてはいけませんが、ヘッドホンを外すと再生デバイスが固定されている仕様のせいか出力はスピーカーにも切り替わらず、ヘッドホンを挿し直してもハヤえもんのシークバーは固まったままになります。』

**Comment by ryutaro** [comment]
WASAPI排他モードを利用した後にアプリケーションの操作ができなくなります。

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1288014807753400321?s=20
ハヤえもんWin版で、起動後にイヤホンを挿してもイヤホンから音が出ないのさすがに直そうかなーと思って軽く調べてみたんだけど、この辺使うのかなーっていうメモ✍️
https://docs.microsoft.com/ja-jp/windows/win32/api/mmdeviceapi/nf-mmdeviceapi-immdeviceenumerator-registerendpointnotificationcallback
