### ISSUE TITLE
[ディスカッション] コントロール画面のX軸の「遅」「速」ボタンをイラストにして欲しい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#235]
日本語では速度変化を意味する「遅」と「速」の一文字ですが、
![resized_01_de8tgi-u0aaft6p](https://user-images.githubusercontent.com/11251874/41396987-a9c54acc-6fed-11e8-86e2-bb581a9f26bf.jpg)

https://twitter.com/ryota_yama/status/997040518935728128
他言語では「遅」が「<<」で「速」が「>>」なっているのを
![resized_ddyzd7euwaam_kd](https://user-images.githubusercontent.com/11251874/41397063-ee0de8e2-6fed-11e8-875a-949459ab2a8f.jpg)

速度を示すイラストにすれば翻訳やソースコード上で切り替える必要がなくなると思うのです。
![resized_ddyzd7fvwaajfuk](https://user-images.githubusercontent.com/11251874/41397112-1c232cba-6fee-11e8-8b32-01a3703b14a7.jpg)
例としてKindleでは「カメ」と「ウサギ」になってます。

他の案としては「徒歩」と「自転車に乗っている人」というのは、いかがでしょうか？
(両方とも人力という意味を含んでます)

### 関連issue：
#229 コントロール画面のX軸とY軸を「♯」「♭」「速」「遅」ボタンと重ならないようにしてほしい

**Comment by arigayas** [comment]
ん？
良太さんの2018年5月18日のツイート
https://twitter.com/ryota_yama/status/997354723886776320
『iPhoneの設定画面もウサギとカメなんだね。
面白いなぁ。』

![resized_voiceover](https://user-images.githubusercontent.com/11251874/41397702-055c56c6-6ff0-11e8-918d-1ca0b87ed43f.jpg)

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
