### ISSUE TITLE
インストーラー版の「聞々 ハヤえもん」が欲しいです。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#236]
ハヤえもんのWeb関係者のチャットワークで話題に上がったので登録します。
インストーラー制作ソフトの策定が必要になりますが。

オイラが愛用している[サクラエディタ](https://sakura-editor.github.io/)だと[Inno Setup](http://www.jrsoftware.org/isdl.php) というのを使っているみたいですね。
紹介記事 ＞＞ [「Inno Setup」オープンソースで開発されるインストーラー作成ソフト - 窓の杜ライブラリ](https://forest.watch.impress.co.jp/library/software/innosetup/)

**Comment by ryutaro** [comment]
最も利用されているのはInstallShieldですかね
でもライセンスがトリッキーで高いです

ハヤエモンのレベルであればWindows Installerは使っても使わなくてもあまり大きな違いは無いと思うので NSISや自己解凍式のアーカイブでも行けそう

後はWindows10以降で新しく使えるようになったMSIX方式も利点があるのですが今のところSDK直接叩くしか作り方無かったと思うので
あんまり手はつけたくないですね

**Comment by arigayas** [comment]
@ryutaro さん、[InstallShield の Wikipedia](https://ja.wikipedia.org/wiki/InstallShield)を見ると

> Visual Studio Communityエディションはサポートされていない

とあるので除外したんだよね。
ハヤえもんのビルドはVisual Studio Communityでもビルドできるのが良いという方針って書いていなくてごめんなさい。
ライセンスがトリッキーって登録が必須って事？

### Windows10以降で新しく使えるようになったMSIX方式
OSのサポートが終わったとしても、しばらく使っている人はいるだろうし、
恐らくMSIX方式を採用した場合にWindows XP～8.1 のインストールが面倒になると思うので採用は否定的かなぁ。

### チャットワークでは、
良太さんがLINE上で**zipファイルのダウンロード先がどこになっているのか、よく解っていないという人**をサポートしたという話があって、
そういう人向けにはインストーラーがあれば懇切丁寧なサポートは不要になるのでは？という事があったんです。
つまり超パソコン初心者向けにインストーラーの需要はあるのではないか？という話です。

**Comment by ryutaro** [comment]
@arigayas 
## InstallShield
まず確認として誰でもビルドできる事が条件であって誰でもインストーラーを作れる事ではないですよね？
バイナリファイルを作った後にそのバイナリを含むインストーラーを作成するので インストーラーを作らなければ問題無いと思います

でもそこじゃなくて InstallShieldのライセンスは50万ぐらいする上にライセンス購入者しか使えない(グループで使うには全員分ライセンスを購入しなきゃいけない)
のでどう考えてもおすすめはしません ただ議論する上での知識としてInstall Shieldもありますよって事で

## MSIX形式
10以外での利用もあるのは想定できますのでmsi形式とmsix形式の二つを用意するのもいいかもしれません(将来的にmsixに完全移行する場合においても ノウハウをためられる)

## チャットワーク
>zipファイルのダウンロード先がどこになっているのか、よく解っていないという人

これはmsi形式かどうかではなく、ウェブサイトのデザインとかそういう事ですか？
(どのリンクを押せばダウンロードできるのか)
それともダウンロードしたzipがどこに保存されているか分からないと言う事でしょうか？
後者の場合はインストーラーになってもダウンロードしたファイルを実行しなければならない点においては同じかと思われます
そして、ブラウザから(1度だけ)実行する事を想定しているのであれば インストーラではなく自己解凍書庫でも十分に目標を達成できるように感じますが、どうでしょうか

自己解凍書庫であれば複雑な設定や複雑なライセンスも不要ですぐに作れそうです

**Comment by arigayas** [comment]
### 64bit版のハヤえもん
@ryotayama 64bit版のハヤえもんを作る予定というか作るつもりはありますか？
もし64bit版のハヤえもんを作るならdllが全て64bit版じゃないと起動しないから対応は必要です。

**Comment by ryotayama** [comment]
@arigayas それほど「遅い」という意見は聞かないから、あまり優先順位が高いとは思ってないけど、64bit版についてもいずれ対応したいなーとは思ってるよ！

**Comment by ryotayama** [comment]
https://twitter.com/jagiovf0/status/1230672663825149952
今日「Windows 10 Home、バージョン 1909」で圧縮ファイル「http://Hayaemon276.zip」を解凍して、中のファイル「Hayaemon.exe」をクリックしたら、無事に「聞々ハヤえもん」が動きました。使い慣れてて「軽快」さは抜群です！
でも、上記の作業はパソコン初心者には簡単にできない気がして心配です。

https://twitter.com/ryota_yama/status/1230673279792250880?s=20
ハヤえもんWindows版、macOS版について、「インストーラー付けて」って声は前からわりとありますね電球
今はスマホの方に注力していてあんまり動けませんが、いつかきっとイイね 

Windows版ならすぐにできるかもしれません_(:3 」∠)_

え、まじで……！？
めちゃくちゃ嬉しい……！号泣

このサイトにあるやり方でvsにツールを追加して、使えばいけそうだなと思いました。
確かはやえもんWinってvsで管理してましたよね？
https://www.osadasoft.com/visual-studio-2017%E3%81%A7%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%A9%E4%BD%9C%E6%88%90/

え、す、すげぇ……！
今の時代って、無料版のvsでも直接インストーラー作れるんだ……！

そうなんすよ、2010くらいには無料で付いてた記憶ありましたけど今もなんか追加できるみたいっす

衝撃を受けすぎた…！
ありがとー、また手が空いた時にでもやってみるね！イイね

https://twitter.com/mikuta0407/status/1230693198948732930?s=20
インストーラ作成試してみたところうまくいきそうでうまくいかなくてふむぅ(出来なくはなかったけどアンインストール時の挙動が変)

たっくんすげぇー！(　ﾟдﾟ)
↓これと同じやり方かなぁ？？
https://twitter.com/12guitar21/status/1230691975650664448

vsじゃなくて、"簡単インストーラ"ってので既存のZipファイルの中身を追加していろいろ設定してる感じですね。
インストールは完璧にできるんですが、アンインストール時に削除していいかの確認をしてくるんです・・・(一応確認はオフにしてるんだけどなぁ)

おぉ、そんなのもあるんだね！電球
情報ありがとー、めちゃくちゃ助かる……！握った手
