### ISSUE TITLE
スマートフォンを機種変更しても機種変前と同じ再生リストを引き継いで欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#237]
アマラ＠Amara1218さんから要望
https://twitter.com/Amara1218/status/1008011371902976002
『初めまして！FF外から失礼致します。
「ハヤえもん」の要望なのですが、スマホの機種を変えても
入ってる曲を引き継ぎ出来る機能をお願いしたいです！
たくさん曲を入れているのであったら助かります！
検討よろしくお願い致します( ᵕᴗᵕ )』

附記：アマラ＠Amara1218さん以外からも同じ要望がある。

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
