### ISSUE TITLE
イコライザ画面がiOS のデザインガイドラインに準拠していない

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#238]
https://twitter.com/ryota_yama/status/1008158505923051520
『これこれー！　他にもあさるとPDFとかいっぱいあった気がする。
44x44がタップしやすい最小サイズらしいから、それに合わせて作ってみる！
https://developer.apple.com/design/tips/jp/ 』

https://twitter.com/ryota_yama/status/1008165011624083457
『そう考えるとさ、再生リストのタブとイコライザのカスタマイズがガイドラインに準拠してない気がする。これも修正ポイントだねー！』

### スクリーンショット
Ver. 2.50 では「つまみの大きさ」や「行間が狭い」のがデザインガイドラインに準拠していない為に誤タップしやすい状態になってる。
![df24us0uyaau_pt](https://user-images.githubusercontent.com/11251874/41505759-8608ec06-724a-11e8-9920-91ebbe08c1e7.jpg)

[ユーザインターフェイスのデザインのヒント](https://developer.apple.com/design/tips/jp/) - Apple Developer
## タップのターゲット
コントロール要素は 44 x 44 ポイント以上の大きさで作成し、
指でも正確にタップできるようにしてください。

**Comment by arigayas** [comment]
iOS 版 Ver.2.54 で対応。

https://twitter.com/UmeboshiKantaro/status/1011273198258622464
『イコライザ（カスタマイズ）のビフォーアフター！！！！((((oﾟ▽ﾟ︎)o)))
スライダーが大きくなってつまみやすくなった感じ！！すてき！！
スクショ繋げたけどとても縦に長い！！笑』

![dgjdnjtu0aatvoi](https://user-images.githubusercontent.com/11251874/41861754-179a555e-78dd-11e8-94ff-0789a440af32.jpg)


変化前はあるので割愛します。

**Comment by ryotayama** [comment]
ver.2.54で対応しました₍₍ (ง*ᐛ)ว ⁾⁾
