### ISSUE TITLE
イコライザの「プリセット」という表記を適切な表現に置き換えたい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#242]
https://twitter.com/umeboshikantaro/status/1009695668451983360?s=21
イコライザの「プリセット」という表記についての素朴な疑問。
「プリセット」は「プリインストール」と同じで、予めセットされたデータを指す用語ではないかと思うので、別の適切な表現に置き換えたいなと思いました！

iOS ver.2.51

**Comment by ryotayama** [comment]
http://e-words.jp/w/%E3%83%97%E3%83%AA%E3%82%BB%E3%83%83%E3%83%88.html

上記リンクを見るとこのように書かれています。

> プリセット 【 preset 】
> 
> プリセットとは、設定値などを前もって調整すること。また、前もって調整された設置値や、その組み合わせ。
> 
> 設定を変更することで機能や性能を調整できる機械やソフトウェアで用いられる概念で、「前もって」の意味によって二つに分かれる。一つは、工場出荷時にメーカーが組み込んだ設定値という意味で、「初期設定」「デフォルト設定」などと同義。
> 
> もう一つは、利用目的や使用環境の違いに応じて複数の設定値の調整が必要な場合に、事前に利用者が調整を行って目的別の設定値のセットを作成し、使用時に一括して設定を切り替えることを意味する。

ハヤえもんで使っている「プリセット」という言葉は、後者の「事前に利用者が調整を行って目的別の設定値のセットを作成」に該当するので、このままでもいいんじゃないかと思われるけど、どーかな？？

**Comment by kengo1228** [comment]
色々なギター用エフェクターを使ってましたが、
出荷時のプリセットとユーザープリセットで保存する場所がわかれていることが多いです。

**Comment by arigayas** [comment]
_スマフォを持っていなから論点ずれているかもですが、_
出荷時のプリセットとユーザープリセットで保存する場所がのままならば、
ユーザーが作成したプリセットは背景色を変えると良いかもしれませんね。

**Comment by kengo1228** [comment]
あ、僕も論点ずれてましたね。
まとめると、
◆プリセットとユーザープリセットで名称分ければ良いのでは？

そして、分けた場合の見分け方については
◆色分け
◆タイトルに細工。
プリセットには『P:』ユーザープリセットには先頭に『U:』とかついてるだけでもわかりやすい。

とか考えました。

Mac版とかはそもそもユーザープリセットは同じリストの中じゃなくて階層が分かれてました。

iOSは縦に一列なので混在する感じです。

**Comment by ryotayama** [comment]
iOS版、Android版ともに対応したのでCloseします！٩( ᐛ )و
