### ISSUE TITLE
イコライザ画面の「並べ替えを終了する」ボタンが下の方の項目とかぶって操作できない部分があるので直してほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#243]
◆使用しているOS：iOS版
◆使用しているバージョン：2.52
◆引用元
https://twitter.com/UmeboshiKantaro/status/1010128557329170432

りょーたさーん！！！！ @ryota_yama 
早速なんですけど、1番下の項目が終了ボタンと被っちゃって操作できないので対応お願いします🙏

**Comment by arigayas** [comment]
MacかiOSで使われている特殊文字が混入していたようなので、それらを削除するためにissue名を変更しました。

**Comment by ryotayama** [comment]
ver2.53で対応しました٩( ᐛ )و
