### ISSUE TITLE
iPadで再生ボタンと再生リストの表示を大きくできるようにしてほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#246]
◆使用しているOS：iOS版
◆使用しているバージョン：2.53
◆内容（FacebookのMessagerにて頂いたご意見）
iPadにてハヤえもんiOS版をライブで使用したところ、再生ボタンや再生リストの表示が小さく、押し間違えのリスクが高いと感じたので、大きく表示させられるようにしてほしい。

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
