### ISSUE TITLE
外部ライブラリのダウンロードを自動化したい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#247]
Windows版のハヤえもんをBuildするにはzipファイルだと17ファイルある外部ライブラリーが必要になりますが、
それらを0からダウンロードするのは、手間なので自動化できれば開発に参加してくれる人の負担が減ると思います。

**Comment by arigayas** [comment]
関連するissue：
#231 外部ライブラリのダウンロードを含むビルド方法をreadmeに記載して欲しい
#240 ハヤえもんWindows版のビルド方法を解説する動画を作る。

**Comment by arigayas** [comment]
@ryutaro さんとチャットワークで話してたら、ダウンロードスクリプトを作ってくれました。
全部で3ファイルです。

1. execute.bat：download.ps1とcopy.ps1を実行するバッチファイル
2. download.ps1：zipファイルをダウンロードするPowerShellファイル
3. copy.ps1：ダウンロードしたファイル操作を実行するPowerShellファイル

これをプルリクか @ryotayama さんがcommitして運用出来るようになったら、いいなと思ってます。

**Comment by arigayas** [comment]
## execute.bat

@echo off
echo 実行中はPowerShellの画面が表示されます
echo 画面には触らずそのままでお待ちください
powershell -ExecutionPolicy Unrestricted ./download.ps1
powershell -ExecutionPolicy Unrestricted ./copy.ps1
cls
echo 処理が完了しました
echo 何かキーを押すと終了します
pause

**Comment by ryotayama** [comment]
わー、ありがとう！
ちょっと動かしてみるね！
これでいけるんだったら、配布ファイルに含めちゃって、これ前提でドキュメント書いた方がいいね₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
これら3スクリプトのバッチファイルである`execute.bat`を`work フォルダ`で実行すると
![image](https://user-images.githubusercontent.com/11251874/41824444-fa2c25ca-784a-11e8-8619-7e3f1ef84da6.png)
上記のスクリーンショットのようにフォルダとファイルが作られます。

`dllsフォルダ` と `libsフォルダ` を別けずに1フォルダにするスクリプトに変えるのもアリかもしれません。

**Comment by arigayas** [comment]
@ryotayama ビルドを試していませんが、たぶんこれで問題ないと思います。
あとは、`,dllファイル` や `.libファイル` を作る必要がある物をどう記述するかって問題ですね。

**Comment by arigayas** [comment]
> あとは、.dllファイル や .libファイル を作る必要がある物をどう記述するかって問題ですね。

これって新規issue登録すべきですが、何が該当しますか？

- libjpeg.lib
- npnez.lib

ざっと思い付いたのは上の2つですが。

**Comment by ryotayama** [comment]
そうだねー！
今出先だから分かんないけど、mp3infpはlibファイル配布されてるんだったっけ？？

**Comment by arigayas** [comment]
下の一覧にないのでmp3infp.lib は使わないのかな？と思ってます。
https://github.com/ryotayama/Hayaemon/issues/231#issuecomment-397020842

**Comment by ryotayama** [comment]
あ、そっかそっか！
ありさん、ありがとー！

**Comment by ryotayama** [comment]
あれ、うまく動かなかった。
コピペミスったかな。
チェックしてみよーっと。

**Comment by ryutaro** [comment]
整形済みテキストとして貼ってないから多分MDとして認識されたのかな？

**Comment by ryotayama** [comment]
ぽいね。今、libjpeg.dllも自動で作るとこまでいけないか、試行錯誤中ー。
