### ISSUE TITLE
Google ドライブからの読み込みに対応してほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#254]
◆使用しているOS：iOS版
◆使用しているバージョン：2.54
◆内容
https://twitter.com/ryota_yama/status/1011431446962028544
#ハヤえもんAppStoreでのやりとり
ちょうどこういうアプリをさがしていました。 ★★★★☆
投稿者: wakaztc – 2018年6月25日
中学校の特別支援学級の担任です。
耳からの情報は処理できるけど、目からの情報がうまく処理できない読字障がいの生徒に教科書本文音声を聞かせるのに使ってます。
スピードもかえられるので、ゆっくりにして本人がふりがなをふる時間を確保できたりと助かっています。
あとは、対応ドライブを増やしていただけると助かります。

開発者さんわざわざ返信ありがとうございます。
僕の希望は①one drive②Google drive

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
