### ISSUE TITLE
逆回転再生メニューをもっと上の方にしてほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#257]
◆使用しているOS：iOS版
◆使用しているバージョン：2.54
◆内容（LINE@でのユーザーサポートより）
逆回転再生機能が気に入っており、使用頻度が高いが、エフェクト画面の下の方にあって、スクロールするのが煩わしいので、もっと上の方に移動させてほしい。

**Comment by UmeboshiKantaro** [comment]
逆回転は私も好きなので、上部の再生コントロール部分に欲しいと思ってました。
結構前のバージョン（1年以上前？）でしたが、再生モードの中に入っていた時期がありましたね。
それもあったので押し間違えやすい「停止」ボタンを廃止するかどうか？みたいなディスカッションがあった時に（issue未登録？）「空いたところに逆回転入れたいなぁ」と思っていました。
でも「再生」ボタンを大きくしてほしいという要望もあるので（#246）逆回転はやはりエフェクト画面なのかなぁとも。

色々考えましたが、逆回転はエフェクト画面の上部に引っ越しするとユーザー贔屓が起きてしまうため、ユーザーが任意で並べ替えできるような仕組みにできた方がいいと思われます。
もしくはお気に入りのエフェクトにスター（☆）をつけられて、自動で上部に配置されるなど。（スターを外すと元の位置に戻る仕組み）

長い！！（笑）

**Comment by ryotayama** [comment]
イコライザとの操作性の統一って意味でも並べ替えに１票₍₍ (ง*ᐛ)ว ⁾⁾

優先順位ちょっと後でいいと思うけど、また画面考えてみてくれるー？？

**Comment by UmeboshiKantaro** [comment]
了解です！！何パターンか作って貼りますね(o`･ω･)ゞ

**Comment by ryotayama** [comment]
ありがとー！！

**Comment by UmeboshiKantaro** [comment]
作りました！

![default](https://user-images.githubusercontent.com/32741225/42068919-a8f89098-7b89-11e8-8fdc-816611807c0b.png)

エフェクト画面の場合、他のメニュー（削除や名称編集など）がないため標準の「並べ替え」アイコンを表示しっぱなしにしておくのがいいと思います。（↑）

一応スターマークのパターンも作ってみましたが、実装が大変そうなのでこちらはボツでいいと思いますw（↓）

![2](https://user-images.githubusercontent.com/32741225/42068962-f51b475e-7b89-11e8-96a4-8b7aca074a2c.png)

ご査収願います<(..)>

**Comment by ryotayama** [comment]
うめちゃん、ありがとー！
並べ替えのみってのは標準機能ではできないみたいだね！
裏技的にはできるっぽいけど。
https://qiita.com/krimpedance/items/c930d808f4eeb12bdb5c

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
