### ISSUE TITLE
コントロールの中央のつまみがボイスオーバーに対応していないので対応してほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#259]
◆使用しているOS：iOS版
◆使用しているバージョン：2.54
◆内容（Twitterより）
https://twitter.com/satoupawapuro12/status/1011623735869050881?s=21

iOSのハヤえもんで要望です。
・コントロールの中央のつまみがボイスオーバーに対応していないので対応をお願いします。
・2つ目の写真の「リセット」ボタンをもう少し大きくしてほしいのと、カギアイコンのオンオフをもう少しわかりやすくしてほしいです。
オフで半透明になるとか？

**Comment by ryotayama** [comment]
重複の為、Closeします₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
後から気付かずに登録してごめんなさい。
