### ISSUE TITLE
コントロールの中央のつまみがボイスオーバーに対応していないので対応して欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#261]
サトウミク＠satoupawapuro12
https://twitter.com/ryota_yama/status/1011750920974004225
『iOSのハヤえもんで要望です。
コントロールの中央のつまみがボイスオーバーに対応していないので対応をお願いします。』

![dgocbervqaagpiv](https://user-images.githubusercontent.com/11251874/41944854-09615894-79e5-11e8-9411-36e1a09f0fcb.jpg)

**Comment by ryotayama** [comment]
#259 と重複かな！

**Comment by arigayas** [comment]
ごめんなさい。重複登録です。こっちをCloseかな？

**Comment by ryotayama** [comment]
Closeします！
