### ISSUE TITLE
鍵アイコンのオンオフをもう少しわかりやすくしてほしいです。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#263]
サトウミク＠satoupawapuro12
https://twitter.com/ryota_yama/status/1011750920974004225
『カギアイコンのオンオフをもう少しわかりやすくしてほしいです。
オフで半透明になるとか？』

![dgocbenu8aakoqh](https://user-images.githubusercontent.com/11251874/41945031-f8342028-79e5-11e8-9c4d-b91029c420ae.jpg)

**Comment by ryotayama** [comment]
対応しました。ver.2.61でリリース予定です٩( ᐛ )و
