### ISSUE TITLE
DirectXのDLLをダウンロードしなければならないのを直してほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#265]
- 使用しているOS：Windows版
- 使用しているバージョン：2.77 β 1
- 内容（メールでのサポートより）
Windows10 バージョン1803 （64ビット）を使用しています。

「Windows Version 2.77 β 1 開発版」（Hayaemon277b1.zip、Hayaemon277b1_XP.zip の両方）で、

Hayaemon.exe を起動しようとすると下記エラーが発生し、起動できません。

「Hayaemon.exe - システムエラー
d3dx9_43.dll が見つからないため、コードの実行を続行できません。プログラムを再インストールすると、この問題が解決する可能性があります。」

このエラーは「Windows Version 2.76 安定版」では発生しません。

ご対応よろしくお願いします。

**Comment by arigayas** [comment]
`d3dx9_43.dll` でWindows版のソースコードをGrepしたら、`xVideo.dll` の中に見つけました。

**Comment by ryotayama** [comment]
ありさん、ありがとー！
公式のフォーラムを見たらこんな記述が。
`xVideo is not longer supported. Please use IVACore.`
これはちょっと調査が要りそうだね！
http://www.un4seen.com/

**Comment by arigayas** [comment]
xVideoのdllとかを差し替えることになりそうって事でしょうか？

**Comment by ryotayama** [comment]
たぶんそーなると思う！

**Comment by ryutaro** [comment]
DirectX って具体的に何に使ってるんですか？

**Comment by ryotayama** [comment]
Windows版には動画を表示する機能（表示→ビデオ画面）があって、それを実装するのにBASS_DSHOWってライブラリを使ってたんだけど、それがxVideoって名前に変わってDirect Xの特定のバージョンが入ってないと使えなくなったって感じかな！

**Comment by DaisukeAtaraxiA** [comment]
ひどまず、Delay loadで時間稼ぎしてはどうでしょうか？

**Comment by ryotayama** [comment]
それはアリですよね！　動画機能使ってる人そんなに多くないだろうし。

**Comment by DaisukeAtaraxiA** [comment]
メインウィンドウの初期化でxVideo初期化しているから、
Delay loadではダメでした。

**Comment by DaisukeAtaraxiA** [comment]
xVideoをシングルトンクラス化して、初めて参照されるときに初期化する、とかが一番簡単ですかね。

**Comment by ryotayama** [comment]
あ、いいですね。xVideoを継続利用する前提なら使わない人は「DLL無い」って怒られないし、使おうとして初めてエラーが出る感じで良さそう。

あとはxVideoを使わない路線として、BASSのフォーラムに書いてあったIVACoreって何やねんってのを調べてみます！

**Comment by ryotayama** [comment]
xVideo.dllが警告を出す為、BASS_DSHOW.dllに戻しました。
またロードタイミングを初回動画読み込み時に変更しました。

**Comment by ryotayama** [comment]
これに伴い、DLL/LIB自動ダウンロードバッチ（getlibs.bat）関連のファイルにも修正が発生しますが、未対応です。
この対応が終わり次第、2.77β3としてリリース予定です！
