### ISSUE TITLE
イコライザのカスタマイズ画面でスライダー間の間隔を空けてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#268]
- 使用しているOS: iOS
- 使用しているバージョン: 2.55
- 内容（ツイッターより）

https://twitter.com/toshiya_c/status/1012299591448911872?s=21

ハヤえもんのEQが非常に操作しやすくアップデートされていました！
以前は帯域押し間違えて「んああああっ！」ということもありましたが、押し間違いがかなり減ると思います。

問題は私が丸や円がたくさん並んでいるのをみることが苦手なことくらいですね。

https://twitter.com/umeboshikantaro/status/1012468655093764096?s=21

隙間なくビッシリってのがウッてなるのわかる

やっぱスライダー5pxずつくらい間隔ほしいな。。

**Comment by ryotayama** [comment]
![Image](https://i.imgur.com/FcJV82c.jpg)

**Comment by ryotayama** [comment]
iOS標準の間隔は8pxだね！
いったんそれで実装してうめちゃんに画面見せまーす！
それで広すぎる（視認性がわるくなる）ようだったら、4pxとかに減らしたりしつつ微調整って感じにしよっか！

**Comment by UmeboshiKantaro** [comment]
登録ありがとうございます！！🙏
「iOS標準の間隔」がある事を初めて知りましたｗ
では一度8pxでお願いします！<(_ _)>

**Comment by arigayas** [comment]
> 問題は私が丸や円がたくさん並んでいるのをみることが苦手なことくらいですね。


_オフトピ　集合体恐怖症って言うのか・・・。_

**Comment by kengo1228** [comment]
そうそう、集合体恐怖症っていうのもあるらしくて、この方がそうかはわからないけどつまむ部分のデザインが違ったら印象かわるのかなーなんておもったり。

**Comment by ryotayama** [comment]
つまみのカスタマイズぐらいなら標準コントロールの範囲でできるみたいだね！
http://iphone-app-program.com/uikit/uislider/slidercustomize/

**Comment by arigayas** [comment]
バーの色がカラフルになったら面白いかもですが、色弱の方への対応が面倒なことになりますね(苦笑)

**Comment by ryotayama** [comment]
あとは常に全部スライダーが表示されてるんじゃなくて、カスタマイズしたい箇所を選んだらスライダー表示に切り替えるとか、図的な表示になってて「＋」「−」ボタンで調整するとかそういうアプローチもあるよね₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
ver2.56にて4px空けるようにしたので、このissueはクローズします。
イコライザのカスタマイズ画面について、そもそもの改善が必要な場合は別issueを立てます。

**Comment by ryotayama** [comment]
変更後のスクリーンショット
![Image](https://i.imgur.com/9jpTysr.jpg)
