### ISSUE TITLE
iOS版： 未対応の FLAC ファイルに対応して欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#271]
Android版をお使いの きゃらくたぁ製作所@Akeyroid7 さんからの要望が発端。
https://twitter.com/Akeyroid7/status/1009813167952707585
『@ryota_yama ふぁぼりつフォローありがとうございます。

アップデート後FLACファイルを再生しようと再生ボタンを押したらフリーズしてしまったのですが、FLACは非対応でしょうか？』

### 関連するissue
 #107 未対応のファイル形式を再生するとクラッシュする。

**Comment by UmeboshiKantaro** [comment]
Android版issueを貼っておきます(*･ω･)ﾉ
https://github.com/ryotayama/Hayaemon_Android/issues/92

**Comment by ryotayama** [comment]
移行済の為、Closeします！
