### ISSUE TITLE
広告を非表示にする機能にキャンセルボタンを追加してほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#275]
- 使っているバージョン: iOS版ver.2.55
- 内容

メニュー→「広告を非表示にする」機能について、一度メニューを選んだ後にキャンセルして元の画面に戻る事ができないので、「キャンセル」ボタンを追加してほしい。

**Comment by ryotayama** [comment]
![Image](https://i.imgur.com/8baeT7n.jpg)

**Comment by ryutaro** [comment]
キャンセルじゃなくてモーダルの外側タップで消えるとかの方が直感的かもしれないですね

**Comment by ryotayama** [comment]
そっか、たしかにそういう手もあるね！

**Comment by arigayas** [comment]
押せるボタンを増やすよりは、ryutaroさんが言っているように「モーダルの外側タップで消えるとかの方が直感的」だと思います。

iPhoneを持っていないから聞くのですが、
広告を非表示にしたユーザーさんの画面には、この機能ってどう表示されるのでしょうか？
_それとも表示されなくなる？_

**Comment by UmeboshiKantaro** [comment]
ありさん、遅くなりましたがすでに広告非表示になっていても項目自体表示されています。

![img_8232](https://user-images.githubusercontent.com/32741225/42409691-0feabeee-8219-11e8-8994-c09d878efe82.jpg)

これ、広告がすでに非表示になっている場合、判定によって「広告を非表示にする」という項目を非表示にすることはできないでしょうか？？
別issueが必要ですかね？？

**Comment by ryotayama** [comment]
判定できるよー！
Issue立てといた！

**Comment by UmeboshiKantaro** [comment]
早い。。！ありがとうございます！！

**Comment by arigayas** [comment]
購入済みなのに表示されているとは思わなかった・・・。

**Comment by ryotayama** [comment]
参考URLメモ
http://an.hatenablog.jp/entry/2017/02/08/210600

**Comment by ryotayama** [comment]
広告を非表示にするダイアログについて、範囲外をタップする事でダイアログが消えるように修正しました。ver.2.60でリリース予定です٩( ᐛ )و
