### ISSUE TITLE
コントロール画面の各ボタンが端に寄りすぎている為、もう少しマージンが欲しい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#276]
- 使っているバージョン: iOS版ver.2.55
- 内容

コントロール画面のボタンについて、端に寄りすぎており、左右はカバーによっては操作しにくく、下は広告の誤タップ、上はくっつきすぎてて窮屈に見える為、もう少しマージンを取るようにしてほしい。

**Comment by arigayas** [comment]
### 関連するissue
#263 ← カバーで隠れていると判別が難しいかもですね。

**Comment by UmeboshiKantaro** [comment]
「遅」「速」「♯」「♭」ボタンにそれぞれ白フチをつけることで改善されるかと思います。

x軸y軸の線とも隙間が空くことによって、よりボタンとして浮いて見える効果が期待できます(*･ω･)ﾉ

![Image](https://i.imgur.com/91TFgHw.jpg)

（↑画像は白フチ4pxにしてあります）

**Comment by ryotayama** [comment]
画面の端との余白にApple公式のガイドラインは無いのかなーと思って探してみたけど見つからなかったので、うめちゃんの案で実装しまーす₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
対応しました。ver.2.61でリリース予定です٩( ᐛ )و

**Comment by UmeboshiKantaro** [comment]
これって鍵ボタンも4pt余白をつけたのでしょうか？？

**Comment by ryotayama** [comment]
鍵ボタンにはもともと4ptの余白がついてた！

**Comment by UmeboshiKantaro** [comment]
了解です！まだタップしにくそうだったら適宜対応していきましょう！👍

**Comment by UmeboshiKantaro** [comment]
あと白フチ指定をやめた経緯がコメントに残っていないと不自然かもしれないので、ツイッターから転載しておきますね！

https://twitter.com/ryota_yama/status/1021745861812875264?s=21
![Image](https://i.imgur.com/tzoubOa.jpg)
なんかちがう₍₍ (ง*ᐛ)ว ⁾⁾

https://twitter.com/ryota_yama/status/1021748084089319425?s=21
![Image](https://i.imgur.com/ebu5sV9.jpg)
![Image](https://i.imgur.com/StTeiq3.jpg)
直してみたけど、まだちがう。速の位置が違うのはさておき、なんかうっすら枠線が残るのは「わしそんな4ポイントなんて枠線に指定されたの初めてでうまく描画しきれないぞ」ってことなのか！？

これうっすら青く見える？？って事は、図の内側に枠線が描画されている可能性があるかも？？
図の外側か中央に線を指定できればうまくいきそうという推測…！

これ描画自体を実装してるわけじゃなくて、ぜんぶiOS標準の機能を使ってるから、たぶんiOS自体の角丸にしてなおかつ枠線を太くした時の挙動がバグってる！
変えようと思うとカスタムコントロール作るしかないんだけど、あまりにも手間が大きいから位置の調整で解決しようかと思案中₍₍ (ง*ᐛ)ว ⁾⁾

そっかぁ💦
そしたらちょい手間かもだけど、ボタンの位置調整と、ボタンとグラフとの間に隙間を作るのがいいかもね…！

うん、ボタンのサイズはもともとのままで、ボタンの内側／外側にそれぞれ4ptずつの隙間を作る路線で考えてみるね₍₍ (ง*ᐛ)ว ⁾⁾

結果的に表示が同じになれば大丈夫さ！！(o`･ω･)ゞよろしくお願いします！！

**Comment by ryotayama** [comment]
ありがとー！　Xcodeで画面の開発をしてるとデフォルトで8ptの余白を取ろうとするから、もしかしたら画面端は8ptのほうがいいかもと思いつつ、グラフの表示エリアがどんどん狭くなるから悩ましいとこだよね。
適宜改善でいいと思います₍₍ (ง*ᐛ)ว ⁾⁾
