### ISSUE TITLE
enum CMDIDのコンパイル時警告を修正

### ISSUE THREAD

**Issue by DaisukeAtaraxiA** [ryotayama/Hayaemon#277]
コンパイル時に、enum CMDIDに関して警告C4091が大量に出力されるので解消する。
警告が大量に出ると、本当に重要な警告が埋もれるため。

**Comment by ryotayama** [comment]
Windows版の方まで見てくださって、嬉しい限りです₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by DaisukeAtaraxiA** [comment]
macOS版の元はWindows版ですから。コードの一貫性のため、macOS版も同様の修正を施します。

**Comment by ryotayama** [comment]
Daisukeさん、ありがとうございます₍₍ (ง*ᐛ)ว ⁾⁾
