### ISSUE TITLE
画像のリソースファイルを\img フォルダを作ってそこへ移動しませんか？

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#295]
恐らく`Hayaemon.rc` の修正が必要になりますが、ソースコードフォルダ直下にある画像ファイル、

- drag_move.cur
- drag_copy.cur
- icon1.ico
- play.ico
- pause.ico
- toolbarS.bmp
- toolbarM.bmp
- toolbarL.bmp

を `\img` フォルダを作ってそこへ移動しませんか？
移動することによってソースコードフォルダ直下が見晴らしが良くなると思うのです。

**Comment by ryotayama** [comment]
大賛成！

**Comment by arigayas** [comment]
`Hayaemon.rc` の修正って直接テキストエディタとかで開いてやるのでしょうか？
Visual Studio ってあまり使ったこと無いからイマイチ使い方がわからないのです。
「試行錯誤してみて」と言うのなら、いろいろ試してみますけど。

**Comment by ryotayama** [comment]
テキストエディタでも編集できるはず！
https://msdn.microsoft.com/ja-jp/library/cc417784.aspx

**Comment by arigayas** [comment]
調べていただきありがとうございます。
ファイルパスの区切り文字がわからないから1つ試しにやってみますね。
実行は明日になると思います。

**Comment by ryotayama** [comment]
はーい₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by DaisukeAtaraxiA** [comment]
手修正かVisual Studioのリソースエディタを使うか統一した方が良いです。
手修正とリソースエディタの生成したrcファイルが必ず一致するとは限りませんので。
