### ISSUE TITLE
［質問］ Visual C++ 8.00 (2003)用のHayaemon.vcproj って使われているのでしょうか？

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#297]
Visual Studio 2017 をビルド環境にしたのなら、
Visual C++ 8.00 (2003)用のプロジェクトファイルって必要なのでしょうか？

**Comment by ryotayama** [comment]
いらないと思う！

**Comment by arigayas** [comment]
他の方からも不要に1票されたら削除かな？

**Comment by DaisukeAtaraxiA** [comment]
加えてVisual Studio 2008のマイクロソフトのサポートは終了しています。

**Comment by arigayas** [comment]
では、削除しますね。
