### ISSUE TITLE
リリースファイルのzipファイル化を自動化したい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#299]
[リリースごとに毎回、手作業でzipファイルを作っている](https://twitter.com/ryota_yama/status/1014668519126921216)と聞いたので、
自動化したらリリース時の手間が減ると思ったので提案します。

### リリース時に作成されているzipファイル

- 通常版（日本語）
- XP対応版（日本語）
- 通常版（英語）
- XP対応版（英語）

自動ダウンロードするのに`バッチファイル`か`PowerShellスクリプト`を作成してzipファイル化するのが良いのでしょうか？
zipファイル化するのに `getlib.bat` で `7-zip` のコマンドラインバージョンをダウンロードしているのでこれを利用するのも良さそう。

**Comment by arigayas** [comment]
zipファイル化するにしても、GitHubのリポジトリに含まれていないファイルとフォルダはどうしましょうか？

### 現時点でリポジトリにないファイル
- `click.wav`
- `manual`
- `sound`

**Comment by ryotayama** [comment]
あ、それgitの管理下に追加した方がいいね！

**Comment by arigayas** [comment]
試しに直下で実行するバッチファイルで作ってみました。

`.backup\7za920\7za.exe a Hayaemon.zip readme.txt`
`cd Relese`
..\.backup\7za920\7za.exe a ..\Hayaemon.zip Hayaemon.exe *.dll

**Comment by arigayas** [comment]
gitの管理下に無いファイルを別のissue登録してそれに#251を関連するissueとして欲しいです。

**Comment by arigayas** [comment]
### バッチファイル叩き台その2
`@echo off`
`if exist ".backup\7za920\7za.exe" (`
`.backup\7za920\7za.exe a Hayaemon.zip readme.txt`
`cd Release`
`rename manual_jp manual`
`..\.backup\7za920\7za.exe a ..\Hayaemon.zip Hayaemon.exe *.dll sound\ manual\`
`rename manual manual_jp`

`echo 英語版を作成します`
`rename manual_en manual`
`..\.backup\7za920\7za.exe a ..\Hayaemon_en.zip Hayaemon.exe *.dll sound\ manual\`
`rename manual manual_en`
`cd ..`
`.backup\7za920\7za.exe a Hayaemon_en.zip readme_en.txt`
`) else (`
`echo 7z.exe file is Not Found.`
`)`
`echo 処理が完了しました`
`echo 何かキーを押すと終了します`
`pause`

**Comment by arigayas** [comment]
英語版はVisual Studio 2017 の「ビルド」→「構成マネージャー」で`English`というのを作って
英語版のビルドを楽できるように出来そうです。
![image](https://user-images.githubusercontent.com/11251874/42410121-a9abe2fa-821f-11e8-932b-4c67311e874a.png)

![image](https://user-images.githubusercontent.com/11251874/42410146-edf10c24-821f-11e8-8648-45c2c0f5f1ea.png)

`English`というのが作られると
![image](https://user-images.githubusercontent.com/11251874/42410177-6b2306b6-8220-11e8-88f5-3c5302bbea76.png)
`English` フォルダに `Hayaemon.exe` ファイルがビルド出来るようになりました。
_現状、設定をしていないので日本語版のハヤえもんWindows版がビルドされてます_

**Comment by arigayas** [comment]
(^-^*)(・・*)(^-^*)(・・*)うんうん

**Comment by arigayas** [comment]
いつか読みたい ＞＞ MSBuild | Microsoft Docs → https://docs.microsoft.com/ja-jp/visualstudio/msbuild/msbuild

> Microsoft Build Engine は、アプリケーションをビルドするためのプラットフォームです。 MSBuild とも呼ばれるこのエンジンには、ビルド プラットフォームでソフトウェアを処理およびビルドする方法を制御する、プロジェクト ファイル用の XML スキーマが用意されています。 Visual Studio は MSBuild を使用しますが、MSBuild は Visual Studio に依存しません。 プロジェクト ファイルまたはソリューション ファイルに対して msbuild.exe を実行すると、Visual Studio がインストールされていない環境で、製品の統合とビルドを実行できます。

**Comment by arigayas** [comment]
自動化する範囲が広がれば手間が減り開発者は楽できますよね(￣▽￣@)

英語版のビルド方法がさっぱり分からないのでどこかに記述をお願いします。
Wikiページかな？

**Comment by ryotayama** [comment]
はーい、子供の寝かしつけが終わったらスクショ撮るけど、プロパティからプリプロセッサってところでJPになってるのをENに変えると英語版がビルドできるよ。

**Comment by arigayas** [comment]
wktk

**Comment by ryotayama** [comment]
## 英語版のビルド方法
1. Visual Studio にて、プロジェクト→Hayaemon のプロパティを選択

![default](https://user-images.githubusercontent.com/6075785/42411311-ab225604-8234-11e8-97f5-68a5af6e8223.PNG)

2. C/C++→プリプロセッサ→プリプロセッサの定義（プルダウン）→編集を選択

![default](https://user-images.githubusercontent.com/6075785/42411322-dd23482a-8234-11e8-8983-ca31b4990bbe.PNG)

3. JPをENに書き換える

![default](https://user-images.githubusercontent.com/6075785/42411325-eb9e02e6-8234-11e8-80a9-51ee629ada40.PNG)

![default](https://user-images.githubusercontent.com/6075785/42411326-efbd091c-8234-11e8-93d1-3ab8d5ac773c.PNG)

**Comment by arigayas** [comment]
試してみます！

**Comment by arigayas** [comment]
ビルド→バッチビルド
![image](https://user-images.githubusercontent.com/11251874/42411769-d7c2cf60-823c-11e8-876c-69355ff1502d.png)

チェックを入れた物だけビルドされます。
![image](https://user-images.githubusercontent.com/11251874/42411763-c48508aa-823c-11e8-93dd-5b773f8f55bf.png)

これでReleaseフォルダと English フォルダに Hayaemon.exe ファイルが一気にビルド出来るようになりました。English フォルダには英語版の Hayaemon.exe が出来てました。

#315 のissueでdll達をdllフォルダにまとめて、リポジトリ直下に置いてそこから
Releaseフォルダ、Debugフォルダ、Englishフォルダへそれぞれのフォルダへコピーした方が起動しやすくなると思いました。

**Comment by arigayas** [comment]
別のissue登録するのが良さそうですね＞4種類のビルドを一気に出来るようにする。

でもそもそも4種類のビルドが必要なのでしょうか？という疑問があります。
XP 版の日本語版と英語版のビルドがあれば、Windows10でも動作するexeファイルが出来るので
十分な気がしてますが、いかがでしょうか？

**Comment by ryotayama** [comment]
ちょっと古いけど、例えばv110、v110_xpの違いで言うと、こんな感じ。
https://blogs.msdn.microsoft.com/vcblog/2012/10/08/windows-xp-targeting-with-c-in-visual-studio-2012/

これで言うと、v110の方はC++ AMPが使えるけど、v110_xpは使えないなんていう風な違いがあって、今使ってるv141とv141_xpにもおそらく何かしらの違いがあると思うんだよね。

そう考えると、XPでも使える要素のみでビルドしたv141_xpの方を全プラットフォームに対して使うよりは、XP以外はv141を使った方がパフォーマンス的にもいいのかなーって感じかな？

**Comment by arigayas** [comment]
恐らくパフォーマンスが違うという事がわかりました。
4種類のビルドを作るので納得しました。

**Comment by DaisukeAtaraxiA** [comment]
別issue(#315)見てて、初めてこのissue見ました。
MSBuildの補足ですけど、やろうと思えば、コンパイルオプションを一時的に変更してビルドするということもできます。
例えば、JPをENに置換してビルド実行、とか。

個人的には、これは少しトリッキーなので、English用構成を作成するのが妥当だとは思いますが、
(非XP/XP対応版)×(Debug/Release)×(日/英) の8パターンになってしまいますね。。

**Comment by arigayas** [comment]
基本的に日本語版でDebugすると思うので、
英語版のDebugビルドは自動生成しなくても良い気がしてますが、どうでしょうか？

**Comment by ryotayama** [comment]
いったん、以下５パターン分の構成を作成する路線で進めます₍₍ (ง*ᐛ)ว ⁾⁾
（それ以外は必要性を感じたら追加という感じで）
①デバッグ、通常版、日本語
②リリース、通常版、日本語
③リリース、通常版、英語
④リリース、XP版、日本語
⑤リリース、XP版、英語

**Comment by arigayas** [comment]
> いったん、以下５パターン分の構成を作成する路線で進めます₍₍ (ง*ᐛ)ว ⁾⁾
> （それ以外は必要性を感じたら追加という感じで）
> ①デバッグ、通常版、日本語
> ②リリース、通常版、日本語
> ③リリース、通常版、英語
> ④リリース、XP版、日本語
> ⑤リリース、XP版、英語

新たにissue登録した方が良いと思います。

**Comment by ryotayama** [comment]
ほんとだ！　ここzipファイル自動化のスレだった！
立てときまーす₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
あっちのissueのコメント： https://github.com/ryotayama/Hayaemon/issues/329#issuecomment-404207347 に書きましたがなるべく多くのファイルをUTF-8にする場合、引っ掛かる可能性があることを書いておきます。

### バッチファイル叩き台その3　ほぼ完成バージョン
`@echo off`
`if exist ".backup\7za920\7za.exe" (`
`.backup\7za920\7za.exe a Hayaemon%1.zip readme.txt`
`.backup\7za920\7za.exe a Hayaemon%1_xp.zip readme.txt`

`rename readme.txt readme_jp.txt`
`rename readme_en.txt readme.txt`

`.backup\7za920\7za.exe a Hayaemon%1_en.zip readme.txt`
`.backup\7za920\7za.exe a Hayaemon%1_en_xp.zip readme.txt`

`rename readme.txt readme_en.txt`
`rename readme_jp.txt readme.txt`

`cd manual`
`rename manual_jp manual`
`..\.backup\7za920\7za.exe a ..\Hayaemon%1.zip manual`
`..\.backup\7za920\7za.exe a ..\Hayaemon%1_xp.zip manual`
`rename manual manual_jp`

`rename manual_en manual`
`..\.backup\7za920\7za.exe a ..\Hayaemon%1_en.zip manual`
`..\.backup\7za920\7za.exe a ..\Hayaemon%1_en_xp.zip manual`
`rename manual manual_en`


`cd ..\Release（日本語、通常版）`
`..\.backup\7za920\7za.exe a ..\Hayaemon%1.zip Hayaemon.exe *.dll sound\`
`cd ..\Release（日本語、XP版）`
`..\.backup\7za920\7za.exe a ..\Hayaemon%1_xp.zip Hayaemon.exe *.dll sound\`

`cd ..\Release（英語、通常版）`
`..\.backup\7za920\7za.exe a ..\Hayaemon%1_en.zip Hayaemon.exe *.dll sound\`
`cd ..\Release（英語、XP版）`
`..\.backup\7za920\7za.exe a ..\Hayaemon%1_en_xp.zip Hayaemon.exe *.dll sound\`
`cd ..`
`echo Releaseファイルのzipファイル化が完了しました`
`) else (`
`echo 7z.exe file is Not Found.`
`)`
`echo 何かキーを押すと終了します`
`pause`


バッチファイル名の後ろにスペースを入れてその後に文字を入れると%1の部分が置き換わります。
バッチファイル名をReleaseZIP.batにした場合、
`ReleaseZIP.bat 278`
で実行すれば

- Hayaemon278.zip
- Hayaemon278_xp.zip
- Hayaemon278_en.zip
- Hayaemon278_en_xp.zip

の出来上がり。

**Comment by arigayas** [comment]
作成したzipファイルを`引数を含むフォルダ`へ移動する機能も追加してcommitしました。

**Comment by ryotayama** [comment]
これめちゃくちゃ便利！！
ありさん、ありがとう₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
これめちゃくちゃ便利！！
ありさん、ありがとう₍₍ (ง*ᐛ)ว ⁾⁾
