### ISSUE TITLE
エフェクトの設定状態を保持した曲について、イコライザのカスタマイズ画面に設定状態が反映されていないのを直したい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#301]
- iOS版ver.2.57
- 内容

以下の手順で不具合発生

1. イコライザ画面でイコライザの設定変更
2. 再生リストの「・・・」メニューからエフェクトの設定状態を保持を選択
3. 別の曲を再生し、イコライザの設定をフラットに戻す
4. 先ほどエフェクトの設定状態を保持した曲を再生すると、イコライザが反映されているが、イコライザのカスタマイズ画面上は反映されていない

**Comment by kengo1228** [comment]
https://twitter.com/kengo1228/status/1014816202516885504?s=21
察したので動画ツイート添付。

**Comment by ryotayama** [comment]
対応しました。ver.2.59でリリース予定です٩( ᐛ )و
