### ISSUE TITLE
Windows版には.DS_Storeは必要のないファイルだと思うので削除したい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#302]
リポジトリ直下にある `.DS_Store` ってMacOSでは、`システムファイル`かつ`隠しファイル`らしいですが、
他のOSでは使われないファイルなのでWindows版のリポジトリから**削除**と**管理下から除外**することを提案します。

**Comment by ryotayama** [comment]
うん、いらない！

**Comment by DaisukeAtaraxiA** [comment]
不要です。

**Comment by arigayas** [comment]
1. `.gitignore` の最後の行に`.DS_Store`を追加
2. `.DS_Store`をエクスプローラーなどで削除
3. `git rm .DS_Store`
4. `git add .gitignore` 
5. `git commit -m "close #302 .DS_Storeの削除"`
6. `git push origin master`

でしょうか？

**Comment by ryotayama** [comment]
1. .DS_Storeをエクスプローラーなどで削除
2. git commit -a -m "close #302 .DS_Storeの削除"
3. git push origin master

だけでもいけるね。

**Comment by arigayas** [comment]
`.gitignore`の編集を入れたのは、_多分ないと思いますが、_
また`.DS_Store`が紛れ込まないように対策を入れておこうかと思ってw

**Comment by ryotayama** [comment]
誰かがMac環境でソースを開いて該当ファイルをaddしない限りは追加されないけど、入れてくれてもいいよ₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
了解しました。
今からやります。

**Comment by ryotayama** [comment]
ありがとー！

**Comment by DaisukeAtaraxiA** [comment]
macOSの方も削除しました。
