### ISSUE TITLE
Dropboxに保存する際、同一名のファイルが存在するとエラーが出る

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#303]
- iOS版ver.2.57
- 内容

https://twitter.com/UmeboshiKantaro/status/1015122157746024448
Dropboxに保存する時に同じファイル名のものがあると、オンラインでもオフラインのエラーが出ました！！

**Comment by UmeboshiKantaro** [comment]
同一ファイル名を避けるために、録音の時みたく保存日時を曲名の後ろに加えるのはどうでしょうか？？

**Comment by ryotayama** [comment]
それでいこう₍₍ (ง*ᐛ)ว ⁾⁾
