### ISSUE TITLE
再生中の曲をシェアできる機能が欲しい（NowPlaying、なうぷれ）

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#311]
- iOS版ver.2.57

https://twitter.com/ryota_yama/status/1015406658992758785?s=21
ハヤえもんから再生中の曲をツイートできるようになったら嬉しい感じ？？

できたら最高に嬉しいですね……❤️

おー、じゃあいずれ対応する₍₍ (ง*ᐛ)ว ⁾⁾
ツイートは手動？？　それとも自動？？

featherの場合は音符マークを押すとこのとおり
そのあとは好きなコメントつけるもよし、コメントなしでツイートするもよしなので、これが手動なのか自動なのかはあやしいのですが……
「 #nowplaying 魂のルフラン by 高橋洋子」
だけは自動で入力されてる感じですかね

なるほどー、あるさんありがとー₍₍ (ง*ᐛ)ว ⁾⁾
うめちゃーん、これやるなら左上のメニューに「再生中の曲をシェア」メニュー追加？？

そうですね、「≡」ボタンに入ったら嬉しいと思います！
いずれ再生中画面を作ったら、そこに加えるのもアリかもしれないです(*･ω･)ﾉ

再生中画面ね！　たしかにそうだ！₍₍ (ง*ᐛ)ว ⁾⁾
じゃあいったん、「三」メニューに「再生中の曲をシェア」入れる段階になったら、画面設計またお願いするね！

かしこまりです！(o`･ω･)ゞ

https://twitter.com/ryota_yama/status/1015409103588376576?s=21
人によって違うからカスタマイズ機能は必須っぽいね！　デフォルトでは「#ハヤえもん」が入るようにしとけば宣伝効果も期待できる？（カスタマイズで削除可能）

**Comment by UmeboshiKantaro** [comment]
issue登録ありがとうございます🙏
画面考えてみます(o`･ω･)ゞ

Dropboxに保存した時のファイル名みたく、音程や速度を載せられると嬉しいですね(*･ω･)ﾉ

**Comment by ryotayama** [comment]
うんうん、ジャケット画像がある時はそれも載せられたらかっこいいなー！
#自らハードルを上げる

**Comment by UmeboshiKantaro** [comment]
#55 と関連付けしておきますね(*･ω･)ﾉ

**Comment by ryotayama** [comment]
ありがとー！

**Comment by ryutaro** [comment]
是非tweetbotへの対応もお願いします

**Comment by ryotayama** [comment]
以下に引っ越した為、closeします！
https://github.com/ryotayama/Hayaemon_iOS/issues/196
