### ISSUE TITLE
ミュージックライブラリから曲を追加する際、同じ曲を何度も追加してしまう為、追加済か分かるようにしてほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#313]
- iOS版ver.2.57

https://twitter.com/tea_0311/status/1015428660143112195?s=21
#ハヤえもん (iOS)にてミュージックライブラリから再生リストに曲を追加する際、タップした回数だけ曲が登録されてあばばばってなります💦

タップの度に追加のチェックを付ける⇔外す、とか
曲の追加自体をやっぱりキャンセル、とかできないでしょうか？
よろしくお願いいたします。

リプライありがとうございます₍₍ (ง*ᐛ)ว ⁾⁾
ミュージックライブラリから曲を追加する時の画面についてはiOS純正の機能を使っているので、直すとなるとオリジナルで画面を作る必要があります。いずれ対応したいとは考えておりますが、時間がかかると思うのでしばらくお待ちくださいね！

**Comment by kengo1228** [comment]
なるほどね、今回みたいにすぐに動けない理由が明示されてるとわかりやすいね。

てっきりチェックボックスくっつけるだけだと思ってた。

**Comment by ryotayama** [comment]
移行済の為、Closeします！
