### ISSUE TITLE
エクスポートできないファイルがあるのでできるようにするか、エラーを出すようにする

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#314]
- iOS版ver.2.57

https://twitter.com/K_Xammo50/status/1015447401790779392

普段自作の曲をラインで共有する時にエクスポートしてるのですが、いつもならFILEって画像の下に容量が表示されて問題なく送信できるのですが、今朝ぐらいから容量が表示されなく送信出来ません😢
どうしたらいいですか？
![1](https://user-images.githubusercontent.com/6075785/42406888-1754240e-81ec-11e8-961e-31c5965367aa.jpg)

あー、容量出ますよね！
急に出なくなりました？　出てた時から出なくなった時までに、何か環境の変化はありましたか？（OSをアップデートした、など）
![2](https://user-images.githubusercontent.com/6075785/42406890-1d6e64c6-81ec-11e8-951d-d75adb8c5098.jpg)

あ、別の曲で試したら出来たので特定の曲でそういうバグ的なものが起こるっぽい感じでした！特にアップデートとかもしてないです！

あ、曲依存なんだ、なるほど！
もし不都合なければその曲を送って頂けたりしますか？？

メッセージ機能からドロップボックス経由で送信します！

ありがとうございます₍₍ (ง*ᐛ)ว ⁾⁾

こちらの環境でも再現できました！
原因究明してみますね！
![3](https://user-images.githubusercontent.com/6075785/42406892-24176e76-81ec-11e8-924a-b92d4dc56db1.jpg)

**Comment by ryotayama** [comment]
この不具合、ようやく原因が分かった！
タイトルに「# 」を含んでいるとエクスポートできないっていう不具合だった！

**Comment by ryotayama** [comment]
対応しました。ver.2.62でリリース予定です٩( ᐛ )و

**Comment by arigayas** [comment]
「他にもあるかも？」と思ってみたり？
例えば「”」や(使えるのか知らないけど)「\」とか、
ハヤえもんのファイル管理の文字に「# 」を使っているんですか？

**Comment by ryotayama** [comment]
iOSの仕様で他のアプリにエクスポートする時に「 # 」を含むファイル名を許してないみたい。
「\」とかそこらへんの文字はもともと置換して消してたんだけど、「 # 」が漏れてた。
他に何があるかは色々調べてたんだけど、分からなかった(*ノﾉ)

**Comment by arigayas** [comment]
今後、漏れがなければ良いですね
