### ISSUE TITLE
ReleaseフォルダやDebugフォルダにあるdllファイル達をdllフォルダへ移動したい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#315]
https://twitter.com/arigayas/status/1015389693834289152
#310 「click.wav」がVS2017の「ビルド」→「Hayaemon のクリーン」を実行すると「click.wav」が消されてしまうので移動させる
がきっかけでhttps://twitter.com/ryota_yama/status/1015391523498651649
『たしかにサウンド系のファイルが直下にあるのも謎だね。そして、ログ系のファイルで消えないやつがあるのも気持ちわるいなぁ。何を消すか、どっかで設定できるのかなぁ。 
あとこの際、dll系もdllsとかいうフォルダに入れるようにしたくなってきた！』

https://twitter.com/ryota_yama/status/1015476779006357504
フォルダ名は『dllでいいと思う！』

関連するissue
 #247 で作成したバッチファイル`copylibs.ps1`を改変が必須になります。
この際、Debugフォルダにもコピーするようにして欲しいと思ってます。

**Comment by arigayas** [comment]
関連するissue
#315 リリースファイルのzipファイル化を自動化したい

**Comment by DaisukeAtaraxiA** [comment]
Hayaemon.exeのフォルダにdllフォルダを作って、そこにbass.dllとかを配置するということでしょうか？
bassはimplicitリンクなわけですが、どうやってパス通します？

ちょっと話は逸れますが、dllやwavなど実行時に必要なものはDebug/Releaseフォルダに
置いてgitで管理するのではなく、Visual Studioのビルド後処理でコピーしてはどうでしょうか？
そうするとDebug/Releaseに２重に置かなくて済みますし、ファイル構成は自然かと思います。

**Comment by arigayas** [comment]
> Hayaemon.exe のフォルダにdllフォルダを作って、そこにbass.dll とかを配置するということでしょうか？

そういう事です。

> ちょっと話は逸れますが、dllやwavなど実行時に必要なものはDebug/Releaseフォルダに
> 置いてgitで管理するのではなく、Visual Studioのビルド後処理でコピーしてはどうでしょうか？

https://github.com/ryotayama/Hayaemon/blob/504dc82577ffccbaf0e4be4837c8fa2a5c29458b/copylibs.ps1#L18-L33
`copylibs.ps1` で `./Release` にコピーしているのを `./dll` に変更して、ここから
Visual Studioのビルド後処理で`Debug/Releaseフォルダ`にコピー出来るなら、コピーすることに賛成です。

**Comment by DaisukeAtaraxiA** [comment]
はい、できます。
後でプルリクエストしてみるので、問題か確認してとらえればと思います。

**Comment by arigayas** [comment]
お願いします。

**Comment by arigayas** [comment]
この[英語版のビルド方法](https://github.com/ryotayama/Hayaemon/issues/299#issuecomment-403208081)と絡みそうですが、これとは切り分けてやる感じでしょうか？

**Comment by DaisukeAtaraxiA** [comment]
プルリクエスト作成しました。
プロパティの、ビルドイベント > ビルド後のイベント、で確認できます。
Debug/Release両方で、実行ファイル作成後にdllが同じフォルダにコピーされます。

同じ要領でReleaseフォルダの、manual_en, manual_jp, soundフォルダも対処できそうです。

![image](https://user-images.githubusercontent.com/5174793/42417250-703071a2-82c0-11e8-9fac-3095c1c97dd3.png)

**Comment by DaisukeAtaraxiA** [comment]
１つ注記です。
Hayaemon.exeと同じフォルダにdllを配置しているだけで、まだHayaemon.exeのフォルダにdllフォルダを置いていません。

技術的に不可能ではないですが、かなりハックなことが必要です。

**Comment by arigayas** [comment]
branch315のzipファイルをダウンロードしてビルドしました。

Debug/Releaseフォルダ両方共にビルド前にはdllファイルが無かったのですが、
ビルド完了時にdll達がHayaemon.exeと同じフォルダに作成されてHayaemon.exeが起動出来ました！！

これは凄い進化ですね！！

**Comment by arigayas** [comment]
dllフォルダを置くようにすると全般的？にソースコードの書き換えが必要になりそうですよね？

**Comment by ryotayama** [comment]
おぉ、ありがとうございます！
早く試したい……！
dllをフォルダに置くのはそんなに難しいイメージじゃなかったんですが、僕が何か思い違いをしてるかな？？
http://blog.syo-ko.com/?eid=1169

**Comment by DaisukeAtaraxiA** [comment]
実行ファイルと異なるフォルダにあるimplit リンクなdllの場合、一般的にプログラムの実行前にパスを通しておく必要があります。
でもそれはシステムフォルダのようなところでないと出来ないですよね？

もし実行ファイル内からパスを通そうとすると、WinMainより前のdllロードロジックをフックする必要があります。

**Comment by ryotayama** [comment]
あ、codeBaseでDLLの場所を指定できるってのは.Netの話なんですね。
だとすると、正攻法ならLoadLibraryで場所を指定して動的に読み込むように修正って感じですかね。
そこまでやるメリットがあるかどうかですね。

**Comment by DaisukeAtaraxiA** [comment]
加えてdllの関数は全てGetProcAddressで取得する必要があります。
何よりBASSがImplicitリンク前提で実装されていたりすると、不具合出たときに厄介ですね。

**Comment by ryotayama** [comment]
よし、dllフォルダに入れるのやめましょう₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
dllフォルダに移動は取りやめるということなのでCloseします。
