### ISSUE TITLE
広告削除に月額制を選べるようにしてほしい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#317]
広告削除について、現在では買い切り方式の2000円しかないですが、
ユーザーによっては「高い」という声もたまにあるので、月額制も選択できるようになると嬉しいです。

現在、App Storeでの最低販売価格が120円なので、1年で1440円です。それだけでもう17ヶ月以上使う人にとっては買い切りのが得になります。

こうした計算ができるユーザーにとっては、2000円で足踏みしていた広告削除に踏み切る可能性があります。

また、結果的に高くついても、月120円の方が支払いやすい、というタイプのユーザーもいるかもしれないので、そういったニーズを満たすのも大事かなと思っています。

ぜひ一度ご検討ください(*･ω･)ﾉ

**Comment by UmeboshiKantaro** [comment]
「広告を非表示にする」
の次のアクションシートで
・月額120円
・買い切り2000円（←もう少し適切な表現があると嬉しい）
と選べるといいんでしょうか？？

#275 とも関連付けしておきますね(*･ω･)ﾉ

**Comment by ryotayama** [comment]
金額出すの多言語化の観点からできるかどうかちょっと分かんないや！
また調べとく！

**Comment by UmeboshiKantaro** [comment]
あー、ドルとかになっちゃうからか…！
よろしくお願いします！

**Comment by ryotayama** [comment]
メモ。いけそうだね。
https://qiita.com/kyasusoft/items/28e48f60f46c32483061

**Comment by ryutaro** [comment]
買い切り=>ライフタイム

2ヶ月に1回とかも確かできたので(本当か？)
調整が必要ですね

**Comment by ryotayama** [comment]
個人的には月額120円はわるくないなぁと思った！

**Comment by ryutaro** [comment]
120円がというより ライフタイム2000円との兼ね合い？

**Comment by guxtuti-raven** [comment]
このissueはリポジトリ名: Hayaemon_iOSに移行されました。
このissueはCloseされます。
