### ISSUE TITLE
左端の再生リストへの曲の移動、コピーができない

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#319]
- iOS版ver.2.57

https://twitter.com/Fridayhasaiko0/status/1015577864819732480

再生リスト1への移動とコピーができません。1から2へはできるんですが…

ご連絡ありがとうございます！
こちらの環境でも確認できました。
修正しますね。

**Comment by kengo1228** [comment]
すぐ対処されるとは思いますが、
参考映像　iOS版ver.2.58
https://twitter.com/kengo1228/status/1017694572745355264

要約すると、
右から左に移動しようとすると一個ずれる、一番左には移動できない。
同内容として追記。

**Comment by ryotayama** [comment]
対応しました。ver.2.59でリリース予定です٩( ᐛ )و
