### ISSUE TITLE
巻き戻しをして曲の頭まで行くと固まってしまう

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#323]
https://twitter.com/umeboshikantaro/status/1015932230605025280?s=21

再生中に前へ（◀︎◀︎）で巻き戻しして曲の頭まで行くと固まります。（曲の頭まで行かなければ再び再生される）

さらにその後一時停止ボタンを押すと、なぜか次の曲が再生される。。

※リンク先では、動画キャプチャを載せています。

ご確認お願いします🙏

**Comment by UmeboshiKantaro** [comment]
https://twitter.com/umeboshikantaro/status/1015939082495541248?s=21

逆回転再生でも同様の現象が発生しました。

ただし、固まった後に一時停止を押すと再生リストの1曲目が再生されます。。

**Comment by ryotayama** [comment]
そのまま再現しましたー₍₍ (ง*ᐛ)ว ⁾⁾
直します！

**Comment by ryotayama** [comment]
対応しました。ver.2.59でリリース予定です٩( ᐛ )و
