### ISSUE TITLE
選択中の再生リストのタブを左端に表示してほしい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#324]
再生リストの一覧画面から曲目画面に移る際、タブが前回選択されていた再生リストの位置のままになっていてわかりにくいことが多いです。

選択された再生リストのタブを、左端（「←」ボタンの右手）に配置してほしいです。

**Comment by arigayas** [comment]
iPhone持ってないから聞くのですが、再生リストを選択中に再生リストを削除って出来るのでしょうか？
削除出来てこれが実装された場合、左端にくる再生リストタブは何が表示されるのでしょうか？

- 再生リストが1つだけの場合
- 再生リストが複数の場合

それぞれで気になりました。

**Comment by ryotayama** [comment]
対応しました。ver.2.59でリリース予定です٩( ᐛ )و
