### ISSUE TITLE
オーディオ出力デバイスを選択できるようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#325]
- Windows版ver.2.77β3

https://twitter.com/gyoza_bass/status/1015197361981685762?s=21

ハヤえもんって再生デバイスの選択はできないのか・・・

Windows版ですか？　現状はできないですね！　いずれ対応したいです！

リプありがとうございます！実装期待しております。開発頑張ってください！

**Comment by arigayas** [comment]
#23 出力デバイスを選択できるようにしてほしい
の重複かな？

**Comment by ryotayama** [comment]
完全に重複してるね！
closeします！
