### ISSUE TITLE
Debug ビルドとわかるようにウィンドウタイトルを「聞々ハヤえもん Debug」になるようにして欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#326]
`#ifdef _DEBUG`
　_ソースコード_
`#endif`

で囲めば出来るみたいですね。

**Comment by ryotayama** [comment]
ありさん、いいね！！
そのまま対応できそうな勢いかな？？

**Comment by arigayas** [comment]
C++の知識は皆無なので対応は無理そうです・・・。

**Comment by ryotayama** [comment]
アプリのタイトルはたしかApp.cppってとこで定義してたと思うよ！
難しそうならこっちでやりまーす₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
### App.cpp

`CApp::CApp(const int & nCmdShow)`
`#if JP`
`	: m_nCmdShow(nCmdShow), `
`#ifdef NDEBUG`
`	m_cstrName(_T("聞々ハヤえもん")),`
`#endif // NDEBUG`

`#ifdef _DEBUG`
`	m_cstrName(_T("聞々ハヤえもん Debug")),`
`#endif`


って書いて今ビルドしてみてます(。・ω・。)ﾉ

**Comment by arigayas** [comment]
上記のコードでビルド出来ました！
![image](https://user-images.githubusercontent.com/11251874/42429858-af5d27d8-8376-11e8-9278-8c9f48cdc174.png)



Delphi初心者だけど似た知識って使える物なんですね。

**Comment by ryotayama** [comment]
おぉ、すごい！
commitしてくれていいよー₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
英語版のDebugビルドでもDebugが付くようにしました。
![image](https://user-images.githubusercontent.com/11251874/42438152-28b37272-839a-11e8-96af-57168bf5714c.png)

_昼間、パソコン部屋が暑くてクーラーのある部屋に退避してました_

**Comment by arigayas** [comment]
何となくローカルリポジトリをGitHubのリポジトリと同じにしようと思って、
まっさらな状態から `git clone ～` をやって `getlibs.bat` を実行すると
`Invoke-WebRequest -Uri http://www.ijg.org/files/jpegsr9c.zip -OutFile jpegsr9c.zip` が失敗してこれ以降がうまくできていなかったです。

どうやらダウンロード先の http://www.ijg.org/ が

> Account Suspended
> This Account has been suspended.
> Contact your hosting provider for more information.

となっており無効になってました。
ってこれは別のissue登録した方が良い案件かもですね(汗)

**Comment by arigayas** [comment]
commitしました。
またCloseするのみすってしまった・・・。

**Comment by arigayas** [comment]
> どうやらダウンロード先の http://www.ijg.org/ が
> 
>     Account Suspended
>     This Account has been suspended.
>     Contact your hosting provider for more information.
> 
> となっており無効になってました。
> 

ダウンロード先の http://www.ijg.org/ は復活したみたいなのでissue登録はしません。
