### ISSUE TITLE
よく使う構成（Debug／Release、通常版／XP版、日本語版／英語版）をあらかじめ登録しておく

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#329]
- WIndows版ver.2.77β3

以下５パターン分の構成を事前に登録しておきます。
①デバッグ、通常版、日本語
②リリース、通常版、日本語
③リリース、通常版、英語
④リリース、XP版、日本語
⑤リリース、XP版、英語

**Comment by arigayas** [comment]
### 関連するissue
#299 リリースファイルのzipファイル化を自動化したい

**Comment by arigayas** [comment]
まさか日本語でフォルダ名が作られるとは思わなかったw
![image](https://user-images.githubusercontent.com/11251874/42556319-2a5eaeb0-8526-11e8-9c53-b96f60679cba.png)



オイラだったら、

- Debug_JP
- Release_EN_XP
- Release_EN
- Release_JA_XP
- Release_JA

にしようとしたと思います。

**Comment by arigayas** [comment]
アルファベットじゃないとコマンドプロンプトなどで操作する時にフォルダの移動が面倒です。

**Comment by ryotayama** [comment]
画面を見たときの分かりやすさと、操作性のトレードオフになりそうだけどどーだろ？？
具体的にはコマンドプロンプトから操作するシチュエーションってあるかなぁ？？

**Comment by arigayas** [comment]
もしも、海外の方が参加するとパスを入力するのに苦労するかと。

**Comment by arigayas** [comment]
入浴中に懸念事項が1つ思い浮かんだんですが、
バッチファイルを作った時にソースコードの差分表示の時に文字化けませんか？

コマンドプロンプトのバッチファイルってUTF-8でも大丈夫でしたっけ？
特にWinXPの頃。

**Comment by arigayas** [comment]
_ここより #299 リリースファイルのzipファイル化を自動化したい の方に書いた方が良いかもですが、_
試しにバッチファイルをUTF-8で作って実行してみたのですが、日本語フォルダだと文字化けが起こってしまって
フォルダの移動が出来なかったです。

実行する文字コードを「chcp 65001」と変更すれば恐らく動きますが、
もしも、海外の方が参加された場合に面倒なことになりそうです。

**Comment by arigayas** [comment]
`git status `を実行したスクリーンショットです。
![image](https://user-images.githubusercontent.com/11251874/42590144-f43ec416-857d-11e8-8030-131df4696c0e.png)
解読は不要だけどもフォルダ名が読めない・・・。

**Comment by DaisukeAtaraxiA** [comment]
Windows標準のコマンドプロンプトだと、
chcp 65001
で文字コードをutf-8に変更できます。
これやらないと、バッチでUNICODE文字なパスへのcdもできないですね。

ちなみに、git-bushやcygwinの端末minttyは、見た目はコマンドプロンプトと
非常によく似ていますが、全く別物のスクラッチから作られた独自の端末ですので
事情は変わってくると思います。

**Comment by ryotayama** [comment]
英語表記に変更したものを先ほどcommitしておきました₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
@ryotayama さん、ありがとうございます。
