### ISSUE TITLE
/Release フォルダに置いてある /manual_jp と /manual_en を/manualフォルダを作ってこちらに移動するのはどうでしょうか？

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#330]
今後の作業を見据えて`/Releaseフォルダ`に置いてある`/manual_jp` と `/manual_en` を
`/manualフォルダ`を作ってこちらに移動するのはどうでしょうか？

gitの管理下では`/manualフォルダ`で管理してビルドする時に `/Release/manual_jp` や `/English/manual_en` フォルダに適宜manualフォルダをコピーするイメージです。
コピーは[Visual Studioのビルド後処理](https://github.com/ryotayama/Hayaemon/issues/315#issuecomment-403232718) の仕組みを使って自動的にコピーする。

### 関連するissue
#299 リリースファイルのzipファイル化を自動化したい
#315 ReleaseフォルダやDebugフォルダにあるdllファイル達をdllフォルダへ移動したい
#329 よく使う構成（Debug／Release、通常版／XP版、日本語版／英語版）をあらかじめ登録しておく

**Comment by ryotayama** [comment]
そうだねー、これもやろっと！
そもそもReleaseフォルダがもはや要らないね。

**Comment by ryotayama** [comment]
soundフォルダも直下に移動させます！

**Comment by arigayas** [comment]
> そうだねー、これもやろっと！
> そもそもReleaseフォルダがもはや要らないね。

確かにビルドする時にReleaseフォルダを生成するからgitの管理下には不要ですね！

> soundフォルダも直下に移動させます！

お願いします。
Releaseフォルダをgitの管理下から削除するなら移動が必要になりますね！

**Comment by ryotayama** [comment]
「manualフォルダは要らないんじゃ？」ってのは、「Visual Studioのビルド後処理の対象としては要らないんじゃ？」という意味なので、ありさんと同意見です。
#299 のバッチファイルに組み込んだ方がいいと思う！

**Comment by arigayas** [comment]
それぞれを
- Hayaemon/manual_en
- Hayaemon/manual_jp
に移動していただけますか？

それぞれのmanualフォルダはzipファイル化する時に組み込むことで良いと思います。

**Comment by ryotayama** [comment]
現状のmanual配下にmanual_jpとmanual_enよりも、直下にmanual_jpとmanual_enの方がいい？？

**Comment by arigayas** [comment]
作業が面倒なら現状のmanual配下でも大丈夫です。

**Comment by arigayas** [comment]
「絶対に」移動して欲しいわけでもないので
現状のmanual配下で良いと思うのでCloseします。
