### ISSUE TITLE
ウェブサイトを hayaemon.jp に引っ越したい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#333]
Windows版、macOS版の配布サイトについて、現状 http://soft.edolfzoku.com/hayaemon2/ で運用しているが、http://hayaemon.jp/ に移転したい。

**Comment by arigayas** [comment]
_別のissue登録するのが面倒なのでここに書きます。_

過去のバージョンをダウンロード出来る一覧ページが欲しいです。

**Comment by arigayas** [comment]
リダイレクトされるので旧サイトの要望WIKIが見られなくなりました。

**Comment by ryotayama** [comment]
全リダイレクトは激しすぎたかw
Wikiは元どおり見られるようにしようかな！

**Comment by arigayas** [comment]
Wikiだけお願いします。

**Comment by ryotayama** [comment]
http://soft.edolfzoku.com/hayaemon2/wiki/index.php
これでアクセスできるかな？

**Comment by arigayas** [comment]
Wikiページ見ることが出来ました！

**Comment by ryotayama** [comment]
移転という意味合いでは完了したので、closeします₍₍ (ง*ᐛ)ว ⁾⁾
