### ISSUE TITLE
再生リスト画面の再生リスト名の縦幅がAppleのガイドラインよりも細いのを修正する

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#338]
- iOS版2.58

再生リスト画面の再生リスト名の縦幅が33pxになっており、Appleのガイドラインである44pxよりも細くなっているので、44pxに変更したい。

![Image](https://i.imgur.com/OLB8z01.jpg)

参考URL: https://developer.apple.com/design/tips/jp/

**Comment by UmeboshiKantaro** [comment]
ポイントとピクセルの違いについて引用させていただきます(*･ω･)ﾉ

http://www.ttui.co.jp/blog/archives/1158
“iOSの場合

単位は「ポイント」です。

非RetinaディスプレイのiPad2とiPad miniで1ポイント＝1ピクセル。

現在主流のiPhone 5やiPhone 6で1ポイント＝2ピクセル。

そしてフルハイビジョンのiPhone 6 Plusで1ポイント＝3ピクセルとなります。”

**Comment by ryotayama** [comment]
対応しました。ver.2.59でリリース予定です٩( ᐛ )و
