### ISSUE TITLE
一時停止中にも巻戻し／早送りができるようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#340]
- iOS版2.58

https://twitter.com/UmeboshiKantaro/status/1018021198922305537
一時停止した状態で早送り／巻き戻ししようと「前へ」「次へ」ボタンを長押しすると、再生されてしまうのを見つけました…！！

https://twitter.com/ryota_yama/status/1018026313066602496
ありがとー！　これはそもそもどういう挙動が望ましいか議論の余地がありそうだね！

https://twitter.com/UmeboshiKantaro/status/1018037254764167168
確かに…！！
個人的には再生中と同じように、長押しで早送り／巻き戻しの動作を期待しましたが、そうじゃないユーザーもいるかもですね…！

https://twitter.com/ryota_yama/status/1018046625619443713
困ったときのiOSデフォルトの挙動！ということで、こんな仕様で別issue立てて対応するね！
①一時停止中も早送り／巻戻しは可能
②一時停止中に早送り／巻戻しした場合は再び一時停止

**Comment by arigayas** [comment]
参考にならないかもですがWindows版 Version 2.77 β 3だと、
一時停止中でも停止中でも、早送り／巻戻しは可能ですね。

**Comment by ryotayama** [comment]
対応しました。ver.2.60でリリース予定です٩( ᐛ )و
