### ISSUE TITLE
逆回転再生を解除して曲の最後まで行くと固まる

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#342]
https://twitter.com/umeboshikantaro/status/1018079220696690688?s=21
逆回転を解除したあと、曲の最後まで行くと固まるのを発見した！！（もう一度再生しようとすると、次の曲が再生されてしまう）

↑リンク先は動画ツイートです。
ご確認いただければ幸いです(*･ω･)ﾉ

**Comment by UmeboshiKantaro** [comment]
通常モード、1曲ループ、全曲ループ、ランダム再生にて共通で確認できました！！

**Comment by ryotayama** [comment]
対応しました。ver.2.60でリリース予定です٩( ᐛ )و
