### ISSUE TITLE
ハヤえもんブログにある「Windows版のハヤえもんの開発までのやり方」をWikiに移植する

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#35]
https://twitter.com/arigayas/status/924921639468273665
ハヤえもんのGitHub の Wikiにもあると良いドキュメントだと思いました。

PC版ハヤえもん 開発までのやり方ってなんじゃらほい? | 聞々ハヤえもん開発者ブログ - http://hayaemon.jp/blog/archives/2674
EXEファイルを作ることを例え話で解説→今日も僕は元気に何かをやっています。 | 聞々ハヤえもん開発者ブログ - http://hayaemon.jp/blog/archives/2341

**Comment by ryotayama** [comment]
対応した٩( ᐛ )و
