### ISSUE TITLE
一時停止時に「前へ」「次へ」を押すと次の曲が再生されてしまうのを、一時停止状態が保たれるようにする

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#352]
https://twitter.com/umeboshikantaro/status/1019144612017987584?s=21
一時停止状態で「前へ」「次へ」を押すと、次の曲が再生状態になってしまうのだけど、これって元からそういう仕様だったっけ？？

ちなみに、iOSのミュージックアプリでは次の曲へ行っても一時停止状態のまま保持されます…！(*･ω･)ﾉ

https://twitter.com/ryota_yama/status/1019147053056880640?s=21
そこ直してないからたぶん元からの仕様だと思うけど、標準に合わせた方がいいね！

↑上のリンク先に動画キャプチャがあります。
どうぞよろしくお願いします(´人･ω･｡)

iOS ver.2.59

**Comment by ryotayama** [comment]
対応しました。ver.2.60でリリース予定です٩( ᐛ )و
