### ISSUE TITLE
再生リストの曲目画面とその他の画面のフォントサイズが合っていないのを統一する

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#353]
https://twitter.com/umeboshikantaro/status/1019146514302578690?s=21
再生リストの曲目画面だけ小さいフォントで、それ以外の画面のフォントサイズと合っていないのが気になっているけど、どうかなぁ？？

![Image](https://i.imgur.com/xBg8Id9.jpg)
![Image](https://i.imgur.com/ZtQmQiQ.jpg)
![Image](https://i.imgur.com/Ugtv27B.jpg)
![Image](https://i.imgur.com/ihyFeuk.jpg)

あー、それ気になる！　全部再生リストの曲名のフォントサイズに合わせようか！

気になるよね💦
あと再生リストの曲目画面だけフォントがボールドになってる…？？気のせいかなぁ？？

あとで確認するー！　ボールドだとしたらそれに合わせる形でいいかな？？

いちどボールド解除したのを確認してみたいです！🙏

ほーい！

iOS バージョン 2.59

**Comment by ryotayama** [comment]
対応しました。ver.2.60でリリース予定です٩( ᐛ )و
