### ISSUE TITLE
バックアップ機能が欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#36]
アンインストールした場合でも再生リストなどを復活できるバックアップが欲しい。

**Comment by arigayas** [comment]
https://twitter.com/ryota_yama/status/927005248270385154

Windows版以外だね。Windows版は内部にファイルを貯めたりしないから。

**Comment by arigayas** [comment]
macOS 版にもバックアップ機能が居ると思うのでラベルを追加しました。

**Comment by UmeboshiKantaro** [comment]
Dropboxにバックアップできるといいという意見が出ましたのでコメント残しておきますね(*･ω･)ﾉ

https://twitter.com/marron_nn_/status/1016971330095230976?s=21
ハヤえもんの再生リストファイルのバックアップ(Dropbox)できる機能、それを書き出す機能欲しいと思った(iPadお絵描きの作業用BGMにしたかった)

**Comment by ryotayama** [comment]
うめちゃん、ありがとー！
これちょっと仕様を考えないといけなくって、再生リストだけを保存したとしても音声ファイルが無いとハヤえもんに読み込めないんだよね。
例えば、端末Ａの再生リストをDropboxに保存して、端末Ｂで読み込んだとしても端末Ａの曲が端末Ｂに入ってなかったら再生できなかったりする。
ここら辺の仕様整理をどうするかってのを検討しないといけないんだけど、自分の中ではまだ答えが出てない感じ！

**Comment by UmeboshiKantaro** [comment]
ありがとうございます🙏

ななすけさんのコメントに続きがありますので載せておきますね。

https://twitter.com/marron_nn_/status/1016973601168244736?s=21
ありがとうございます！
１曲ずつの書き出しは大変なのでリストごと行きたいというそれだけです…(*´`*)

https://twitter.com/umeboshikantaro/status/1016986289864732672?s=21
わかります…！！
ただ、曲のボリュームによって時間がかかってしまうかもしれないです…！その辺も含めて検討してみますね！！🙏

https://twitter.com/marron_nn_/status/1016990798347317248?s=21
時間かかってもいいのでとりあえずはあるとうれしいですね！
もう改善リスト沢山あってめちゃくちゃ大変なのは分かってるので、ほんと休み休み頑張ってください…！！！

以上です。
既存の一曲ごとの保存やエクスポート機能の、再生リストバージョン、というイメージのようです。

もし実装できるなら、私も返信しましたが曲のボリュームによってはかなり時間がかかる可能性がありますよね。
現在の曲の保存やエクスポートは、一度実行して保存中やエクスポート中のバーが表示されると「キャンセル」を選択することができませんが、「キャンセル」できるようにするのも大事になってくるかと思います。

ご検討ください(*･ω･)ﾉ

**Comment by ryotayama** [comment]
ふむふむ！
だとすると拡大解釈すると、「複数曲をまとめて保存する機能が欲しい」にも近いのかなぁ？？

**Comment by UmeboshiKantaro** [comment]
たしかに、複数曲の選択ができるようになったらまとめて保存／エクスポートできるのもいいかもしれないですね。
ななすけさんの話的には、再生リストの一覧画面の「…」ボタンのアクションに保存／エクスポートを追加できないかなーという感じですね(*･ω･)ﾉ

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
