### ISSUE TITLE
再生リスト画面、イコライザ画面の並べ替え中にラベルのサイズを動的に拡大するようにしたい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#361]
- iOS版2.59

再生リスト画面、イコライザ画面の並べ替え中のラベルについて、余白がたくさんあるのに「…」と省略されてしまう為、動的に拡大するようにしたい。
![2018-07-18 18 26 03](https://user-images.githubusercontent.com/6075785/42872659-74dffb00-8ab8-11e8-8dea-9d5831d697cc.png)
![2018-07-18 18 27 20](https://user-images.githubusercontent.com/6075785/42872665-788050c0-8ab8-11e8-9e4e-cf4314c93dda.png)

**Comment by UmeboshiKantaro** [comment]
再生リスト画面に関しては、並べ替えだけでなく通常でも鍵アイコン分のスペースが空いてしまっているので、そこを動的に伸縮処理するのがいいと思います(*･ω･)ﾉ
関連issue⇒ #185

**Comment by ryotayama** [comment]
あ、関連づけありがとー₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
対応しました。ver.2.61でリリース予定です٩( ᐛ )و
