### ISSUE TITLE
録音の保存時にアーティスト名の入力欄を設けてほしい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#366]
#365 に関連して。

![Image](https://i.imgur.com/p27nav8.jpg)

録音の保存時にはアーティスト名を入力する欄がないので、入力欄を設けることを提案します。

加えてですが、以前 #134 にて誕生日を祝う機能がほしいという要望がありましたので、ユーザー名を含むプロフィール情報を保存できる機能があれば、録音時のアーティスト名に利用できていいなと思います。

ご意見頂戴したいです(*･ω･)ﾉ

**Comment by ryotayama** [comment]
賛成でーす！
必須項目じゃないからユーザー側の手間は変わんないし、付けるデメリットが何も無いね₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
対応しました。ver.2.61でリリース予定です٩( ᐛ )و
