### ISSUE TITLE
各画面の名称変更機能や削除機能など、表記が整っていない部分を合わせたい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#371]
#370 に関連して。

画面ごとに名称変更や削除などの機能の表記が違う部分を整えたいです。

## 1.  名称変更機能

再生リストの曲目画面:
「タイトルとアーティスト名を変更」

再生リスト一覧画面:
「再生リストの名前を変更する」

* 変更する or 変更
* 再生リストの名前→再生リスト名？

## 2.  削除機能

再生リストの曲目画面:
「削除」

再生リスト一覧画面:
「再生リストを削除する」

イコライザのプリセット画面:
「削除」

* 削除 or 削除する
* 「〇〇を」は必要かどうか？

ご意見頂戴したいです(*･ω･)ﾉ

他にもありましたらコメントお願いいたします🙏

**Comment by ryotayama** [comment]
うぉー、うめちゃんありがとう！！

名称変更は

再生リストの曲目画面: 「曲名とアーティスト名を変更」

再生リスト一覧画面: 「再生リスト名を変更」

が良さそうだね！

**Comment by UmeboshiKantaro** [comment]
記法が間違っていたのと、一部内容を勘違いしていた部分がありましたので本文を修正しました🙇‍♀️

りょーたさん→そうなんですよ…「再生リストを空にする」だけ浮いてるんですよね…ちょっと悩ましいので削除もそのままでいいかなという気がしてきています(；-ω-)ゞ

**Comment by ryotayama** [comment]
この話面白いね₍₍ (ง*ᐛ)ว ⁾⁾

ちなみに本文はなにか変わったかな？？

![Image](https://i.imgur.com/t04mEO9.jpg)

**Comment by UmeboshiKantaro** [comment]
スクショありがとう🙏
「タイトルとアーティスト名を変更」のところが「曲名とアーティスト名を変更」になっていたので、正しい表記に直しました💦

**Comment by ryotayama** [comment]
いったん「再生リストの名前を変更する」を「再生リスト名を変更」に変更するっていう対応でこのIssueは閉じて、他にも気になる点があればIssueを立てるという方向性にしようと思うけど、どーかな？？

**Comment by ryotayama** [comment]
おっけー！　それでいきます₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
対応しました。ver.2.61でリリース予定です٩( ᐛ )و
