### ISSUE TITLE
起動時ではなく再生を押してからバックグラウンド音声が切り替わるようにしてほしい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#372]
ハヤえもんを起動すると、まだ「再生」を押していなくてもバックグラウンド音声がハヤえもんに切り替わってしまうので、「再生」を押してから切り替わるようにしてほしいです。

標準のミュージックアプリや、YouTubeアプリの挙動では、起動だけでは切り替わらず再生時に切り替わるようになっていますので、同様の挙動にお願いしたいです🙏

**Comment by ryotayama** [comment]
対応しました。ver.2.61でリリース予定です٩( ᐛ )و
