### ISSUE TITLE
端末で文字サイズを大きく指定していると、タイトルとアーティスト名変更のテキストが途切れてしまうのを改善したい。

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#374]
![Image](https://i.imgur.com/Fyff6Il.jpg)

https://twitter.com/satoupawapuro12/status/1020551816801443841?s=21
に対してのコメント

そもそもフォントサイズ変えてると「タイ…」「アー…」みたいな感じなんですね(*ノﾉ)
そっちも直さなきゃ！！

たしかに「・・・」で隠れてしまっていますね。僕はあまり気になりませんが、ユーザーさんによってはきになる方もいるかもしれませんね。

**Comment by UmeboshiKantaro** [comment]
![Image](https://i.imgur.com/G2fSHeL.jpg)

現在入力欄の中に入ってしまっているラベルを外に出して

タイトル
［入力欄］
アーティスト名
［入力欄］

という風に、折り返して表示されるようにする、というのはどうでしょうか(*･ω･)ﾉ

**Comment by ryotayama** [comment]
あ、それいいね₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
メモ
https://stackoverflow.com/questions/37695744/uilabel-in-uialertcontroller-or-uitextfield-alike-uilabel

専用のオリジナル画面を１つ作るしか方法が無い為、開発にかかる時間を考え、いったん後回しにします₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
ツイッターで話し合った結果、プレースホルダーがあればラベルは不要という話になったので、ラベルを消す方向で対応します₍₍ (ง*ᐛ)ว ⁾⁾
![Image](https://i.imgur.com/M64xOm6.jpg)

**Comment by ryotayama** [comment]
対応しました。ver.2.61でリリース予定です٩( ᐛ )و
