### ISSUE TITLE
アプリの説明文に改行を入れる

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#379]
-  iOS2.60

アプリの説明文が読みづらいので、改行を入れます！

![Image](https://i.imgur.com/xWiQL0w.jpg)

**Comment by ryotayama** [comment]
あ、しまった。これ対応忘れてた。
次回はきっと！

**Comment by arigayas** [comment]
これって別にバージョンアップ(審査)とは関係ないんでしょうか？
無関係ならば今日中にやることにしてはいかがでしょうか？

**Comment by ryotayama** [comment]
それが審査のタイミングでしか変えられないんだよねー！
忘れないようにしないとね。

**Comment by arigayas** [comment]
そうなんですね(´・ω・`)
ちょっと面倒くさいですね・・・。

**Comment by UmeboshiKantaro** [comment]
close漏れかな？？

**Comment by ryotayama** [comment]
対応しました٩( ᐛ )و
