### ISSUE TITLE
音楽プレーヤーと音楽プレイヤーの表記が混在しているのを修正する

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#380]
-  iOS2.60

音楽プレーヤーと音楽プレイヤーの表記が混在しているのを修正します！

修正時には直し漏れが無いよう、必ず全文検索する事！

![Image](https://i.imgur.com/p6p0u2w.jpg)
![Image](https://i.imgur.com/HrQj4Qd.jpg)

**Comment by arigayas** [comment]
_アプリの検索する時にここの言葉が検索される対象に含まれているのか知りませんが、_
ふと、表記がバラバラなせいで検索にヒットする可能性があるかも？と思いました。

**Comment by ryotayama** [comment]
対応完了しました₍₍ (ง*ᐛ)ว ⁾⁾
