### ISSUE TITLE
カメラロールから音声を読み込む時にタイトルとアーティスト名を入力できるようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#382]
- iOS2.60

カメラロールから音声を読み込む時に再生リスト上のタイトルが意味不明な文言になってしまう為、タイトルとアーティスト名を入力できるようにしたい。

**Comment by arigayas** [comment]
現状どんなUIですか？スクリーンショットをお願いします。

**Comment by ryotayama** [comment]
ほーい₍₍ (ง*ᐛ)ว ⁾⁾
![Image](https://i.imgur.com/Z72YstE.jpg)
![Image](https://i.imgur.com/Vc9TIpj.jpg)
![Image](https://i.imgur.com/JMnb7DU.jpg)

**Comment by arigayas** [comment]
### これは改善しないとですねw

**Comment by ryotayama** [comment]
でしょ！？笑

**Comment by ryotayama** [comment]
対応しました。ver.2.61でリリース予定です٩( ᐛ )و
