### ISSUE TITLE
広告表示状態の挙動をテストする為、テスト版については広告の表示を復元できるようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#384]
- iOS2.60

広告表示状態の挙動をテストする為、テスト版については広告の表示を復元できるようにしたい

**Comment by ryutaro** [comment]
これ言っといてなんですが、実際の機能とは関係ない機能持たせると
変な所でバグ起きそうなので どちらかというと 設定のエクスポートインポートで環境を元に戻せるようにした方がいいですね

そうするとアンインストールも手軽にできますし

**Comment by ryotayama** [comment]
あー、これは正論！！　この発想好き！！

**Comment by aafxaa** [comment]
「広告の表示の復元」については↓。

ハヤえもんiOS版、課金で広告を非表示にしている場合でも、広告を再表示できるようにしたのを含む、２点の対応を行ったver.3.75をリリース！
http://hayaemon.jp/blog/archives/7943

「設定のエクスポートインポート」については↓。

ハヤえもんiOS版、変数などの容量が1MBを超える場合でもiCloudにバックアップできるようにしたのを含む３点の対応を行ったver.3.68をリリース！
http://hayaemon.jp/blog/archives/7868

もしかしてクローズ可能?

**Comment by ryotayama** [comment]
ほんとだー、クローズします！👍
