### ISSUE TITLE
再生中でなくても歌詞が表示できるようにしてほしい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#391]
#245 の関連です。

現在、再生中の曲しか歌詞が表示できないため、再生中以外でも歌詞が表示できるようにしてほしいです。

再生リストの「…」アクションシート内に歌詞のメニューを設けることができると嬉しいです。

ご意見頂戴したいです(*･ω･)ﾉ

**Comment by ryotayama** [comment]
対応しました。ver.2.62でリリース予定です٩( ᐛ )و
