### ISSUE TITLE
歌詞のタイトル上下に罫線をつける

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#392]
歌詞画面のタイトルの上下に罫線がないため、エフェクトのオプション画面と同様の罫線をつけてほしい。

【歌詞画面】
![img_8809](https://user-images.githubusercontent.com/32741225/43185224-3a69e9b8-9026-11e8-8e5b-0e747904433e.PNG)

【エフェクトのオプション画面（パン）】
![img_8812](https://user-images.githubusercontent.com/32741225/43185257-5739624e-9026-11e8-89ef-a26f68e47c20.PNG)

iOSバージョン2.60

**Comment by ryotayama** [comment]
対応しました。ver.2.61でリリース予定です٩( ᐛ )و

**Comment by arigayas** [comment]
どう変わったのか気になります。

**Comment by ryotayama** [comment]
歌詞が載せれないので、上の方だけ₍₍ (ง*ᐛ)ว ⁾⁾
![Image](https://i.imgur.com/L3vM8Tl.jpg)

**Comment by arigayas** [comment]
なるほど！これはデザイン的に必要ですね

**Comment by ryotayama** [comment]
だよねー、デフォルトで入ってくれてもいいぐらい₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
(^-^*)(・・*)(^-^*)(・・*)うんうん
