### ISSUE TITLE
歌詞表示ボタン画像がRetina表示に対応していない

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#394]
歌詞表示ボタン画像がRetina表示に対応していないので画像を変更してほしい

![img_8811](https://user-images.githubusercontent.com/32741225/43185956-51c493d6-9028-11e8-8c82-b1d829302925.png)

iOSバージョン2.60

**Comment by ryotayama** [comment]
対応しました。ver.2.61でリリース予定です٩( ᐛ )و
