### ISSUE TITLE
コントロール画面の速度／音程のロックについて、前回終了時の状態を引き継ぐようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#397]
- iOS2.60

https://twitter.com/ryota_yama/status/1022399178587033601

#ハヤえもんAppStoreでのやりとり
ひとつだけ…… ★★★★★
投稿者: ouR/Y – 2018年7月19日
ひとつだけ…我儘をば……
コントロール画面の速度、音程をデフォルトでロック状態にしてほしいです
キーを変えようと思ったときに、しばしばミスタッチしてしまいえらいことになるので…
私以外の大多数ユーザーがアンロック状態の方が使いやすいと感じているのであれば、このレビューはなかったことにしていただいて構いません

いつも重宝しています、ありがとう

デベロッパの回答 – 2018年7月26日
ouR/Yさん、ありがとうございます！　りょーたです٩( ᐛ )و
なるほど、ご意見ありがとうございます。
コントロール画面の速度／音程のロックについて、前回終了時の状態を引き継ぐようにするというのがいいかもしれませんね。
前向きに考えてみます！
他にも何かありましたら、いつでも連絡くださいね。
ツイッター（@ryota_yama）から連絡頂く事もできます！

**Comment by ryotayama** [comment]
対応しました。ver.2.62でリリース予定です٩( ᐛ )و

**Comment by UmeboshiKantaro** [comment]
テストの仕方をメモしておきますφ(･ω･｡)

https://twitter.com/umeboshikantaro/status/1024222787693502465?s=21
4って、テストの仕方これで合ってる？？

ロックしてないのがデフォルトだから、きっちりテストするなら、以下４パターンかな！
①速度オン、音程オン
②速度オン、音程オフ
③速度オフ、音程オン
④速度オフ、音程オフ

↑の状態で再起動をかけて、速度音程ともに設定が残っていればOKとの事です！
