### ISSUE TITLE
「別の再生リストにコピー」だけでなく、同一再生リスト内にもコピーできる機能がほしい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#412]
「別の再生リストにコピー」だけでなく、同一再生リスト内にもコピーできる機能がほしいです。

アクションシート上での表記を

「別の再生リストにコピー」⇒「コピー」

にして、コピー先に現在の再生リスト名が表示されるのが嬉しいと思います(*･ω･)ﾉ

下記ツイートからのリプライ参照です。
https://twitter.com/ryota_yama/status/997300504819462145?s=20

あ！コピーは再生リスト内にもコピーできるのでは！？！？
そんな分岐なかったっけ、あ、なかった(*ﾉﾉ)

現状はできないね！

エフェクト類のステータスが違う同じ曲を同じ再生リスト内で作るときに便利そうですね

それ思った！！！！

おっけー！　じゃあいずれ、コピーは同一再生リスト内でもできるようにしましょうかね！

それすごく嬉しい…！！🙏

**Comment by ryotayama** [comment]
対応しました。ver.2.62でリリース予定です٩( ᐛ )و
