### ISSUE TITLE
再生中の曲が削除されると次の曲が即座に再生されてしまうので、一時停止になってほしい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#413]
再生中の曲が削除されると次の曲が即座に再生されてしまうので、一時停止になってもらえると嬉しいです！

再生中以外の曲が削除された場合は、再生状態のままで大丈夫です。

iOSバージョン2.61

**Comment by ryotayama** [comment]
移行済の為、Closeします！
