### ISSUE TITLE
【相談】「ランダム再生」という言葉について

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#434]
- iOS版ver.2.62

ハヤえもんiOS版に搭載されている「ランダム再生」って、もしかして「シャッフル再生」ですかね？

https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q148443564

**Comment by UmeboshiKantaro** [comment]
これは「ループ」or「リピート」という問題もありますよね。

現在iOS標準のミュージックアプリではアイコンのみの表示で、名称が書かれていませんが（以前のバージョンでは書かれていた）、iTunesでは共通して「リピート」「シャッフル」の名称が使われています。

参照: 音楽を再生／リピート／シャッフルする - Apple サポート
https://support.apple.com/ja-jp/HT207230

ここは「挙動については、iOS用のMusicアプリを参考にして作成しています。」という開発方針に則って、iTunesで使われている「リピート」「シャッフル」に変更するのがベターかと思います(*･ω･)ﾉ

https://github.com/ryotayama/Hayaemon/wiki/iOS-%E7%89%88%E3%81%AE%E4%BB%95%E6%A7%98%E3%81%AE%E5%82%99%E5%BF%98%E9%8C%B2

**Comment by ryotayama** [comment]
あー、基準があるっていいね！
「シャッフル」は了解です！

「ループ」についてはABループにもハネるけど、ハヤえもんWindows版の時代から「ABループ」という名前で馴染んでるユーザーさんが多数いそうなので、ABループはABループのままで、再生モードのループだけ「１曲リピート」「全曲リピート」に変更という整理でどうでしょう？？

**Comment by UmeboshiKantaro** [comment]
「ABループ」に関しては、１つの曲の中でループする別機能なので、そのままで問題なしという認識ですね(*･ω･)ﾉ

* 「1曲ループ」→「1曲リピート」
* 「全曲ループ」→「全曲リピート」

でお願いいたします🙏

**Comment by UmeboshiKantaro** [comment]
念のため、「ABループ」と「ABリピート」どちらの名称が一般的か、Google検索の結果件数の差などを見て判断されるのがベターかと思います(*･ω･)ﾉ

**Comment by ryotayama** [comment]
おっけーです！
ちなみに現状の「ランダム再生」を「シャッフル」に変更、でいいかな？（シャッフル再生だと文字数的に入らない）

**Comment by UmeboshiKantaro** [comment]
「ランダム再生」→「シャッフル」でOKです◎
6文字までOKです？？
とすると「1曲リピート」「全曲リピート」は文字数セーフかな？？

**Comment by ryotayama** [comment]
その認識！！
試してみるね₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
Hayaemon_iOS の方に引っ越したので、こちらはcloseします！
https://github.com/ryotayama/Hayaemon_iOS/issues/6
