### ISSUE TITLE
【相談】コントロール画面の操作性について

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#435]
- iOS版ver.2.62

コントロール画面のグラフ部分をタップすると速度と音程を二次元のグラフで変更することができます。

この際、小数（速度123.4%、音程♯1.5など）になると何だか気持ちわるくてローラーで微調整したりしています。

何か良い解決策は無いものでしょうか？？

**Comment by UmeboshiKantaro** [comment]
グラフ上での操作では小数点以下を反映しないようにしてはいかがでしょうか？？(*･ω･)ﾉ

ローラー選択によってのみ小数点以下を指定できる、という風に。

**Comment by ryotayama** [comment]
ドラッグ中に吸着したらカクカクするだろうから、指を離したタイミングで一番近いところに吸着とかかなぁ？？
しかし、「グラフで連続的にいじれるのが良かったのに台無しです」って人が多発しそうな予感もする(*ノﾉ)

**Comment by UmeboshiKantaro** [comment]
なるほど。台無しにならないために小数点以下のオンオフ切り替えができれば良いのかな…？？

**Comment by ryotayama** [comment]
その方がベターな気はするね！
ちなみに補足情報として、ハヤえもんWindows版は（おそらくそれを移植したmacOSも）、小数点桁数を0桁、1桁、2桁から任意で選択できるようになってます。

**Comment by UmeboshiKantaro** [comment]
その３つから選べるのはすごい( ﾟωﾟ；)
iOSでもかゆいところに手が届くようにしたいですね💪

**Comment by ryotayama** [comment]
そろそろ設定画面の作りどきかなぁ？？
歯車アイコン押すと各種設定ができる画面みたいな。

**Comment by UmeboshiKantaro** [comment]
設定画面は他の要望（例えば夜間モードなど）の実装の際にも必要になりますね(*･ω･)ﾉ
歯車アイコンの設定画面は、ドロワーメニュー（引き出し式のサイドメニュー）を実装してからその中に配置になるかと思います。

**Comment by ryotayama** [comment]
メニューの個数に制限を無くした上で設定画面を作るという方針、大賛成です₍₍ (ง*ᐛ)ว ⁾⁾

個人的に設定画面がグチャグチャになってるアプリ（どこで何を設定できるかよく分からないようなアプリ）はあまり好きじゃないので、そこらへんのバランスは要調整だね！

**Comment by UmeboshiKantaro** [comment]
#220 にコメントしておきました(*･ω･)ﾉ

**Comment by ryotayama** [comment]
移行した為、Closeします٩( ᐛ )و
