### ISSUE TITLE
再生モードの表示を直感的にわかりやすくしたい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon#436]
たまに「リピート再生やシャッフル機能はどこですか？」などの質問がきます。
これは再生モードの表示が直感的に分かりにくいため問い合わせが起きていると思われます。
UIの改善が必要ですねφ(･ω･｡)

https://twitter.com/ryota_yama/status/1025189939804221440?s=21
ご連絡ありがとうございます！
１曲ループ、ありますよ₍₍ (ง*ᐛ)ว ⁾⁾

↑鍵垢さんだったので質問が取得できませんでした💦

https://twitter.com/ryota_yama/status/1025800294305656832?s=21
「通常モードって何やねん」と思ってタップしない人が、１曲ループやランダム再生の存在に気づかないという問題への対処法とは？？

https://twitter.com/aki_00010/status/1025802042361532420?s=21
連続再生モード、
リピートモード、
シャッフルモード、とかいうのは

https://twitter.com/ryota_yama/status/1025802504536117250?s=21
ありがとうございます！
「連続再生」ね！
「通常モード」よりは分かりやすいかも₍₍ (ง*ᐛ)ว ⁾⁾

〜〜〜〜〜〜〜〜

例えばiOS標準のミュージックアプリでは、シャッフルとリピートが分かれていて背景色の変化によってオンオフが視覚的にわかるようになっています。

![Image](https://i.imgur.com/JWhkr28.jpg)

![Image](https://i.imgur.com/lvQykWy.jpg)

![Image](https://i.imgur.com/CB78AaK.jpg)

![Image](https://i.imgur.com/CNn9hVW.jpg)

ハヤえもんの場合スペースの都合で難しいですが、仮にシャッフルとリピートを分離できたとしても「1曲のみ」があぶれるので悩ましいですね…。

ご意見頂戴したいです(´人･ω･｡)

**Comment by ryotayama** [comment]
オンオフ系で行くなら、こんな感じかなぁ？？
- 連続再生
- リピート
- シャッフル

例えば連続再生がオフで、かつシャッフルがオンの場合は、「未再生の中から無作為に次の曲が決まるけど、再生は始まらない」みたいな新しいパターンも副産物としてできるね。

**Comment by UmeboshiKantaro** [comment]
オンオフの概念を取り入れるには根本的なレイアウト変更が必要になってしまうので、ひとまず手軽に実装できる
「通常モード」→「連続再生」
という名称変更はやってみる価値ありそうですよね。。！φ(･ω･｡)

**Comment by ryotayama** [comment]
ではいったんこのIssueでは、「通常モード」を「連続再生」に変えるという方針にして、それ以上の対応は別Issueを立てる方針にします₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
Hayaemon_iOS の方に引っ越したので、こちらはcloseします！
https://github.com/ryotayama/Hayaemon_iOS/issues/5
