### ISSUE TITLE
カウントを入れてから再生を開始する機能がほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#453]
https://twitter.com/moonsky1001/status/1027713423797190656

3カウントいれてから音楽再生できるようにできないですか！！！！

**Comment by kengo1228** [comment]
3カウントって
1、2、3、ハイ、ドーン
のことなのか
1、2、3、ドーン
のことなのかどっちなんだろう。

**Comment by ryutaro** [comment]
iTunesがギャップレス再生用のメタデータ持ってませんでしたっけ？

**Comment by UmeboshiKantaro** [comment]
過去にも同様の要望のやり取りがありますので掲載しますφ(･ω･｡)
（鍵垢さんなので現在ツイートのURLを取得できません💦わかりにくくて申し訳ないです🙏）

楽器演奏者としては曲の前にカウント入れれるようになったら自分にとって最強のアプリになる...
そのタイミングも微調整とかもできたら尚嬉しいです...

なるほどー！　ありがとうございます！　検討してみますね٩( ᐛ )و

私はドラムやってるんですが音楽に合わせて練習する時、ドラムから始まる曲になるとどうしても最初合わせることが難しかったんですよね...
期待して待ってます( ´ ▽ ` )

なるほどー。練習時に入りにくいんですね！　とは言え、自動テンポ解析は結構難易度高いんで、手動で……ってなるとうーん。悩ましいですね！　インターフェース勝負だなぁ。いかに分かりやすくその機能を画面に組み込めるか……。やりたいことはすごく良く理解できました！٩( ᐛ )و

私はBPMは各自で測定する感じで大丈夫だと思います(BPM解析はハイレベルすぎる笑)
曲の頭に空白がある曲があるので0.1秒単位で曲にカウントを食い込ませる(？)ことができれば理想です...

とりあえず考えてみました！
メトロノームのデザインはGoogleで検索したやつほぼそのままです笑
かゆいところに手が届くといいのですが…。

![Image](https://i.imgur.com/EMPZJab.jpg)

ほとんどこれで大丈夫だと思います！
ですが、曲の頭にほんの少しでも空白が入ると再生前のカウント数が調節できても必ず曲の0:00からカウントが始まるならズレてしまうのでは？と思います...
なので空白をトリミングorカウントを後ろにズラすように微調整できる機能が必要だと感じます

曲頭の空白をなくせば解決するので調節機能をつけるよりカットの方がシンプルで良いかもしれませんね
途中スタートでカウントは一時停止から再生時にカウントを入れられるようにすれば良いし

現在、ABループを保存する機能がないんですよねー。
曲名長押しオプションメニューの「エフェクトの設定状態を保持」のところでABループも保存できれば…
Aの位置を空白後に設置し、そこから再生で解決できるかと思います…(*･ω･)ﾉ違うかな？

あってる！

それで問題ないと思います！

ほんとですね！気づきませんでした
それならメトロノームのズレの問題はもう解決ですね

**Comment by UmeboshiKantaro** [comment]
当時の提案では、曲名長押しによるメニューでしたが、現在だと「…」のアクションシート内に「nカウント後に再生」という項目を設ける感じになると思います。

そして #220 に上がっている歯車アイコンの設定画面にて、ユーザー側で何カウントかを設定できるようにするのがいいと思われます。（デフォルト値は要検討）

曲の前にある空白については、現状だとABループを設定した状態で「保存／エクスポート」をすることによって実現できるかと思います。

他にいい案がありましたらコメントお願いいたします(´人･ω･｡)

**Comment by ryutaro** [comment]
無音部分はプログラム的にかなりの精度で探せると思うので曲追加時に解析してそれをデフォルト値として使い
最大で1拍分動かせたら事足りるかなと思います

拍のデフォルトは4/4が基本(?)だと思うので4が妥当かなと思うのですが、あまり詳しくないので広く意見を聞きたいですね

**Comment by ryotayama** [comment]
https://github.com/ryotayama/Hayaemon_iOS/issues/756
↑に移行したのでCloseします
