### ISSUE TITLE
エクスポートが機能しなくなることがある

### ISSUE THREAD

**Issue by ryutaro** [ryotayama/Hayaemon#457]
条件がよくわからないけど、カメラロールに保存ってした後に同じ曲をもう一度保存しようと起きるのかな？

一度発生すると曲を変えたりしてもだめだけどアプリ殺してからやり直すと動く

**Comment by ryotayama** [comment]
@ryutaro これも再現しないなぁ。。何か特定の条件がありそうだったら、教えてもらえると嬉しいです！！

**Comment by ryutaro** [comment]
エクスポート完了後
> カメラロールに保存しました
が出るまでにラグがある場合があって
その表示が出る前に操作を開始すると以降操作が正しくできなくなる事が分かりました

**Comment by ryotayama** [comment]
@ryutaro さん、ありがとう！
再現及び、修正できました！

**Comment by ryotayama** [comment]
対応しました！　ver.2.65でリリース予定です٩( ᐛ )و
