### ISSUE TITLE
LAMEの同梱化について

### ISSUE THREAD

**Issue by mikuta0407** [ryotayama/Hayaemon#477]
MP3のソフトウェア特許が2017年に切れ、AudacityのようなソフトもLameを標準で同梱するようになったので、Lameの同梱化なんていかがでしょう･･･?

**Comment by ryotayama** [comment]
https://twitter.com/nao_7cherries/status/1286259389662298112?s=20
あーやっぱりLAME入ってないとmp3出せないのね、ハヤえもん君も…
まあAudacity用に入ってたから問題ないけどLAMEは入ってた方が嬉しいかもしれんな…
