### ISSUE TITLE
マルチユーザーに対応するためSetting.iniの格納先をユーザーごとのフォルダに変更したい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#478]
マルチユーザーに対応するためSetting.iniの格納先をユーザーごとのフォルダに変更します！
（SHGetSpecialFolderPathにCSIDL_LOCAL_APPDATAを渡せば取れるのかな？）

これを対応しないと将来的にインストーラー形式で配布した際にProgram Filesにインストールされると、権限によってはSetting.iniが書き込めない✍️

**Comment by aafxaa** [comment]
関連会話の記録:

@ryota_yama 聞々 #ハヤえもん win2.77β4 Windows10
曲を追加して立ち上げ直すと曲の追加が無かったことになるのですが仕様でしょうか?
https://twitter.com/cranberry_talks/status/1284114979415711748
↓
クランベリーさんありがとー、それユーザーさんからも連絡もらって自分の環境で再現できなかったやつだ…！
Windows版はHayaemon.exeと同じディレクトリにSetting.iniってファイルが自動作成されてそこに曲の情報が書き込まれる想定なんだけど作られてないかなぁ？
https://twitter.com/ryota_yama/status/1284115503913418754
↓
ini出来てないです。

C:\Program Files(x86)\Hayaemon に解凍。
C:\Program Files(x86)にフォルダ作成するには管理者権限必要。

exe右クリックメニュー「管理者として実行」すると、D&Dの曲追加は出来なくなるのですが、終了時にiniが出来るようになりました。
書込権限あるとこに解凍しないとですね
https://twitter.com/cranberry_talks/status/1284120933276372992
↓
あー、なるほど…！　だから正常に動く人と毎回リセットされちゃう人がいるのかー！
ありがとう！
https://twitter.com/ryota_yama/status/1284126037891153920
