### ISSUE TITLE
ハヤえもんの公式サイトのリニューアル

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#49]
https://twitter.com/UmeboshiKantaro/status/927527154077745152

機能要件をここで討論か決まったことをメモしていこう。

**Comment by arigayas** [comment]
FAQの作成

- 全般
- Windows版
- iOS版
- Android版

**Comment by arigayas** [comment]
うめさんのデザイン案：https://twitter.com/UmeboshiKantaro/status/901804072390483968

**Comment by KBone12** [comment]
某所で対応を会議することにしました

**Comment by KBone12** [comment]
close 49
