### ISSUE TITLE
メトロノームの機能が欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#50]
https://twitter.com/tocotoco5656/status/917008939010613248
「楽器演奏者としては曲の前にカウント入れれるようになったら自分にとって最強のアプリになる...
そのタイミングも微調整とかもできたら尚嬉しいです...」

うめぼしさんによる追加機能の画面デザイン案：https://twitter.com/UmeboshiKantaro/status/917035837484761088

**Comment by arigayas** [comment]
今更ながら画面デザイン案を添付して「スケッチ」ラベル付与。
![metronome_dln3ovevyaaddu5](https://user-images.githubusercontent.com/11251874/41709787-0c7c6b6e-757f-11e8-81af-5988ec6dfcb0.jpg)

**Comment by ryotayama** [comment]
メトロノーム機能は実装できると思うけど、nカウント後に曲再生については、「実際の曲とメトロノームがずれる」って問題が発生しそうだね。（解決策を思いついてないけど、いったん懸念事項として）

**Comment by ryotayama** [comment]
メトロノーム、効果音シリーズと同じ扱いでエフェクト画面に入れるってのはどーかなぁ？？

**Comment by UmeboshiKantaro** [comment]
完全に同意というか、全く同じことを考えててコメントしようと思ってました！！
「ひとまず機能をつけてみる」という意味では、標準のスライダーでBPM調整ができれば良いなと思ってます(*･ω･)ﾉ

**Comment by ryotayama** [comment]
よし、付ける₍₍ (ง*ᐛ)ว ⁾⁾
バグもだいぶ減って土台がしっかりしてきた印象を受けてるハヤえもんiOS版！

**Comment by ryotayama** [comment]
対応しました。ver.2.62でリリース予定です٩( ᐛ )و
