### ISSUE TITLE
iPhone機能追加：アルバム一覧画面

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#51]
この機能追加の画像を作成するの発端のツイート：
https://twitter.com/mikuta0407/status/915571974339833856

![albumlist](https://user-images.githubusercontent.com/11251874/32501472-6f12651e-c41b-11e7-997f-617a0b207978.jpg)

## アルバム一覧画面で必要な機能：
- ソート(アルバム名、発売日)
- 単語検索欄
-- 単語検索欄では何を検索の対象にするのでしょうか？
- アルバムのジャケット画像のサムネイル
- アルバム名を表示
-- アルバム名をタップすると「アルバム個別画面」を開く
- アーティスト名を表示
- アルバムの曲数

## アルバム個別画面で必要な機能：
- 「アルバム一覧画面」に 戻る ボタン
- アルバムのジャケット画像
- アルバム名を表示
- アーティスト名を表示
- アルバムの曲数
- 発売日 or 発売年を表示
- 曲名リスト
- 各曲に対して歌詞データがあれば歌詞カードアイコンを表示する
- 各曲の長さを[分分分:秒秒]表示

**Comment by arigayas** [comment]
再生ボタンは不要？

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
