### ISSUE TITLE
iPhone機能追加：アーティスト名一覧画面

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#52]
![artistlist](https://user-images.githubusercontent.com/11251874/32502725-dd5330be-c41e-11e7-8bc7-559b00d858a3.jpg)

# アーティスト名一覧画面で必要な機能：
## アーティスト名一覧画面ヘッダー部分：
- ソート(アーティスト名、発売日)-
- 単語検索欄
-- 単語検索欄では何を検索の対象にするのでしょうか？
--- 対象は曲名、アーティスト名、発売日の全部？
## アーティスト名一覧画面リスト表示部分：
- アーティストの最新のジャケット画像のサムネイル
-- Amazonにアクセスして取得?それともハヤえもんがインストールされているデバイスにあるアルバムのジャケット画像？
- アーティスト名を表示
-- アーティスト名をタップすると「アーティスト名個別画面」を開く
- アーティスト名で検索して表示される所持している曲数

# アーティスト名個別画面で必要な機能：
## アーティスト名個別画面ヘッダー部分：
-「アーティスト名一覧画面」に 戻る ボタン
- アーティスト名の最新のジャケット画像
- アーティスト名を表示
- アーティスト名で所持しているアルバム数を表示
## アーティスト名個別画面リスト表示部分：
- リストの何番目かを表示
- 各曲が収録されているアルバムのジャケット画像
- 各曲の曲名を表示
- 各曲が収録されているアルバム名
- 各曲に対して歌詞データがあれば歌詞カードアイコンを表示する
- 各曲の長さを[分分分:秒秒]表示

**Comment by arigayas** [comment]
「再生ボタン」を押した場合にどのように再生する物を選択するのでしょうか？

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
