### ISSUE TITLE
iPhone機能追加：再生リストの画面

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#53]
![playlist](https://user-images.githubusercontent.com/11251874/32504102-5c443ae6-c422-11e7-8716-1c35b0036424.jpg)

# 再生リスト一覧画面で必要な機能：
## 再生リスト一覧画面ヘッダー部分：
- ソート(再生リスト名、発売日)-
- 単語検索欄
-- 単語検索欄では何を検索の対象にするのでしょうか？
--- 対象は曲名、アーティスト名、再生リストの作成日、再生リスト名の全部？
## 再生リスト一覧画面リスト表示部分：
- 再生リスト名を表示
-- 再生リスト名をタップすると「再生リスト個別画面」を開く
- 再生リストの曲数
- 画面右下に「新規作成」ボタンを表示
--「新規作成」ボタンをタップすると「再生リスト個別画面」を開く

# 再生リスト個別画面で必要な機能：
## 再生リスト個別画面ヘッダー部分：
-「再生リスト一覧画面」に 戻る ボタン
- 再生リスト名を表示
- 再生リスト名をタップすると再生リスト名を編集出来るようになる
## 再生リスト個別画面リスト表示部分：
- リストの何番目かを表示
- 各曲が収録されているアルバムのジャケット画像
- 各曲の曲名を表示
- 各曲が収録されているアルバム名
- 各曲に対して歌詞データがあれば歌詞カードアイコンを表示する
- 各曲の長さを[分分分:秒秒]表示
- 画面右下に「曲を追加」ボタンを表示
--「曲を追加」ボタンをタップすると「iTunes/Dropbox/カメラロール」などから選択できる

**Comment by arigayas** [comment]
再生リストで関連すると思うのでコメント追加： #188

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
