### ISSUE TITLE
iPhone機能追加：全曲再生画面(停止中)

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#54]
![allsongs](https://user-images.githubusercontent.com/11251874/32505232-0a789cd6-c425-11e7-9ad3-a17377354f07.jpg)

# 全曲再生画面で必要な機能：
## 全曲再生画面ヘッダー部分：
- ソート(曲名、発売日)-
- 単語検索欄
-- 単語検索欄では何を検索の対象にするのでしょうか？
--- 対象は曲名、アーティスト名、曲名の全部？

## 再生リスト個別画面リスト表示部分：
- 各曲が収録されているアルバムのジャケット画像
- 各曲の曲名を表示
- 各曲が収録されているアルバム名
- 各曲を演奏しているアーティスト名
- 各曲に対して歌詞データがあれば歌詞カードアイコンを表示する
- 各曲の長さを[分分分:秒秒]表示

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
