### ISSUE TITLE
iPhone機能追加：歌詞カードの画面

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#57]
いろいろなところにある歌詞カードアイコンから開かれる画面。
![wordsofsong](https://user-images.githubusercontent.com/11251874/32509858-f559dfec-c431-11e7-93b7-39061b9fae2f.jpg)

- 開いたリストに戻るボタン
- 曲名が収録されているアルバムのジャケット画像
- 曲名を表示
- 各曲が収録されているアルバム名
- 発売日：YYYY年MM月DD日
- 作詞：作詞者名
-- 作詞者名のデータが存在しない場合はどうしますか？
- 作曲：作曲者名
-- 作曲者名のデータが存在しない場合はどうしますか？
-歌詞データ
- 恐らく1画面に収まらないので縦のスクロールバー

**Comment by arigayas** [comment]
ビットレート表示
する機能をどこかに追加すると良いかも。

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
