### ISSUE TITLE
スプラッシュスクリーン(ハヤえもんを起動したらすぐに表示される画像)が欲しい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#58]
https://twitter.com/Pikamu_W7/status/927877086034800640

iPhone版やAndroid版の起動時に間があるので起動作業中なのか不安になるので
ハヤえもんを起動したらすぐに表示される画像が欲しい。

検索語：

- スプラッシュスクリーン，splash screen
- ローンチスクリーン, launch screen
- スプラッシュ画面

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
