### ISSUE TITLE
左カットや右カットのエフェクトの新設。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#59]
左カットや右カットのエフェクトの新設。
- この機能は左カットor右カットON、OFFで機能するのではなくレベル（数字）を指定できるようにする。
-- https://twitter.com/ryota_yama/status/928082848338157568

対象OSは全てのOS[Windows / iOS / Andoroid]。

## 参考URL
- https://twitter.com/ryota_yama/status/928082614858145792
- [ 『右と左』の哲学が始まった。あなたの右は本当に右なのか？ ](http://www.kengo-kitajima.net/entry/2017/11/08/140721)
- https://twitter.com/guxtuti_raven/status/928082482561302528
- https://twitter.com/guxtuti_raven/status/928082794768621568

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
