### ISSUE TITLE
再生中、iPhoneマイクからの音声がモニターできる機能

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#63]
https://twitter.com/nekobasu_sax/status/929137505898598401

再生中、iPhoneマイクからの音声がモニターできる機能が欲しいです。
私はこの機能を楽器練習に使いたいのですが、カラオケの練習としても需要があると思います。
さらにエコー等のエフェクトがかけられれば最高です。

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
