### ISSUE TITLE
エラーメッセージがEnjoy your Musicになってる

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#7]

**Comment by ryotayama** [comment]
https://twitter.com/kengo1228/status/917961922905038849

**Comment by arigayas** [comment]
![image](https://user-images.githubusercontent.com/11251874/32698767-180ea3aa-c7ee-11e7-85de-20289118453d.png)


正しくは「Enjoy “Your” Music」だったんですね。
http://hayaemon.jp/blog/archives/2898

**Comment by arigayas** [comment]
https://twitter.com/ryota_yama/status/937253689340739584
「(指摘は)あってる！　ついでにwith Hayaemonも付けようと思ってる！」

**Comment by ryotayama** [comment]
次のバージョン（ver2.00）で直る予定！٩( ᐛ )و

**Comment by arigayas** [comment]
https://twitter.com/ryota_yama/status/939543183653871616
iPhone版のエラーメッセージ画面

![resized_dqntilvuqaeugy2](https://user-images.githubusercontent.com/11251874/33797786-4faff250-dd51-11e7-9fa5-616350a7b250.jpg)

Dropbox
![resized_dropbox](https://user-images.githubusercontent.com/11251874/33797787-4fdbe3b0-dd51-11e7-99fd-83f97c078e00.jpg)
