### ISSUE TITLE
OneDrive からの読み込みに対応して欲しい

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#74]
https://twitter.com/P1_sT3/status/936431203279704064
「Onedrive のアイコンを増やして そこから取り込めるようになってほしいなぁ」

![_s](https://user-images.githubusercontent.com/11251874/33469302-720e2d42-d6a5-11e7-951b-7efcc1d8412d.png)

**Comment by guxtuti-raven** [comment]
issue移行したため、このissueはCloseします。
