### ISSUE TITLE
ABループの時間表示が見切れてる

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#75]
4インチサイズ[iPhone 5/5c/5s/SE ]のスクリーンショット
![img_8839](https://user-images.githubusercontent.com/11251874/33473309-427d40e0-d6b9-11e7-8b7f-0c9f18c6a462.PNG)

画面スケール変更で4.7インチサイズ[iPhone 6/6s/7/8]のスクリーンショット
![img_8838](https://user-images.githubusercontent.com/11251874/33473310-43cc1f70-d6b9-11e7-852d-a506ab80c23a.PNG)

バージョン 1.97にて確認。

**Comment by ryotayama** [comment]
対応しました。ver.2.60でリリース予定です٩( ᐛ )و
