### ISSUE TITLE
「アプリ情報」画面がほしい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#76]
Webページリニューアルスタッフ間のチャットより。

**Comment by arigayas** [comment]
## 仕様要件には
### 文字情報として

- ソフト名：ハヤえもん
- バージョン：
- 作者名：
- 配布場所：

### 画像として

- ロゴ

が必要でしょうか？

**Comment by arigayas** [comment]
#162 このissueと関連しますね。

**Comment by UmeboshiKantaro** [comment]
ひとまず左上メニューに置けるかな。ネーミング的にはaboutより「アプリ情報」がいいかもね。

**Comment by ryutaro** [comment]
設定画面の中にも欲しいかも
序でにバグった時用のオールリセットボタンもこのあたりに欲しい気が

**Comment by arigayas** [comment]
iOS での名称と Android での名称は両方とも「アプリ情報」で良いのかな？
それぞれのOSの作法的に。

**Comment by arigayas** [comment]
あと、大多数のユーザーには無関係な機能かもですが、
- 広告非表示機能：取得済みか否かを表示

を文字情報として表示するのを追加するのはいかがでしょうか？

**Comment by ryotayama** [comment]
いったんiOS版について、対応しまーす٩( ᐛ )و
内容についてもまずはバージョン番号が分かる必要最低限のレベルで実装します！

**Comment by arigayas** [comment]
良太さんが今、iOS版 のアプリ情報画面でバージョンをコピーする機能を実装中だけど、
コピーするのにあると便利そうな情報を考えてみた。

- ユーザーがハヤえもんで使用しているiPhoneは何か？を取得(例：iPhone 5 / iPhone SE / iPhone 6 等)
- 使用しているiOS のバージョン
- (余計かもしれませんが) 空き容量のサイズ

思い付いたのはこんな感じです。

**Comment by arigayas** [comment]
とある方からのTwitterでいただいた情報
iPhoneの情報
https://gist.github.com/adamawolf/3048717

モデルナンバー一覧
Models - The iPhone Wiki → https://www.theiphonewiki.com/wiki/Models

**Comment by ryotayama** [comment]
iOSバージョンの「ハヤえもんについて」画面を追加したバージョンをハヤえもんver.2.48としてリリース予定です٩( ᐛ )و
◆日本語
![img_4087](https://user-images.githubusercontent.com/6075785/41018679-f55f29b6-6995-11e8-8468-33d4e763b096.PNG)
![img_4088](https://user-images.githubusercontent.com/6075785/41018681-f7ba57ee-6995-11e8-99b5-99f066684f3a.PNG)
![img_4089](https://user-images.githubusercontent.com/6075785/41018684-f96eba80-6995-11e8-86c5-f9de3f037485.PNG)
◆日本語以外
![img_4093](https://user-images.githubusercontent.com/6075785/41018685-facdb3ea-6995-11e8-8506-847cc1bc9add.PNG)
![img_4094](https://user-images.githubusercontent.com/6075785/41018689-fc6c1d40-6995-11e8-9c53-12d79aec63e4.PNG)
![img_4095](https://user-images.githubusercontent.com/6075785/41018690-fd82550a-6995-11e8-88e7-6cc59f4ceb6e.PNG)

**Comment by arigayas** [comment]
良い感じですね！

**Comment by ryotayama** [comment]
iOSバージョンの「ハヤえもんについて」画面を追加したバージョンをハヤえもんver.2.48としてリリースしました٩( ᐛ )و

**Comment by ryotayama** [comment]
これいったん対応したので、クローズします₍₍ (ง*ᐛ)ว ⁾⁾
画面に何かを追加したいときは別イシューで対応します！

**Comment by arigayas** [comment]
Hayaemon_Android/issues の方にissue登録しておきますね。
