### ISSUE TITLE
ロック画面で一時停止→再生と操作した後、画面に戻ると一時停止のままになっているのを直してほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#83]

**Comment by arigayas** [comment]
バグ報告のツイート
https://twitter.com/guxtuti_raven/status/938963057803386880
「ロック画面のみ検証
ハヤえもんで再生中にロック画面から一時停止→再生と操作
ハヤえもんを起動
一時停止のままになってる」

**Comment by ryotayama** [comment]
対応しました。ver.2.60でリリース予定です٩( ᐛ )و
