### ISSUE TITLE
Dropboxにある曲を読み込んでいる間に再生リストを変更しようとするとアプリが落ちる“不具合を直してほしい。

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon#89]
Twitterにてご連絡頂きました！٩( ᐛ )و
https://twitter.com/mizuki1235/status/939926912763281408

**Comment by arigayas** [comment]
今更ですがTwitterでのコメントを書きます。


ささと @mizuki1235 さんのコメント
『環境 iPhone7 iOS11.2 アプリVer2.00 において、
”Dropboxにある曲を読み込んでいる間に再生リストを変更しようとするとアプリが落ちる“不具合です。
起動後一度でもそのDropbox内の曲の再生に成功している場合は起こらないようです。』

**Comment by ryotayama** [comment]
対応しました。ver.2.62でリリース予定です٩( ᐛ )و
