### ISSUE TITLE
イコライザのインポート機能/エクスポート機能が欲しい。可能なら共有機能も。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#93]
https://twitter.com/ryota_yama/status/943981910295953408
『そういう意味ではイコライザのインポートエクスポート機能をつけたいよね。「こんなイコライザ考えたんだけど良くない？」「なにこれすげー！」みたいなコミュニケーションが生まれるといいよね。』

https://twitter.com/Risowa19/status/943983695844728832
『イコライザのインポートエクスポート機能 とか良いなぁ…』

https://twitter.com/ryota_yama/status/916579135392063489
『ついでにエフェクトとかコントロール系もエクスポート／インポート機能をつけようかと……！』

https://twitter.com/ryota_yama/status/916581327834464256
『URLにしよーかと思ってるんですよね。
http://hayaemon.jp/equalizer/hFjnCsH … みたいな（未実装）
そこにアクセスすると自動的にハヤえもんにインポートさせるようにしようかと思ってます』

**Comment by ryotayama** [comment]
https://github.com/ryotayama/Hayaemon_iOS/issues/12
に引っ越したのでcloseします！
