### ISSUE TITLE
再生リストの再生終了後の表示がおかしい

### ISSUE THREAD

**Issue by mikuta0407** [ryotayama/Hayaemon#94]
再生リストをリピートせずに再生し、最後の曲が終わった後、ロック画面に表示されてる情報がおかしい
・まだ最後の曲が再生されている判定に
・その曲の再生時間が異常なことに
(iOS9のため、10や11での挙動と異なっている可能性があります。)
![img_9095](https://user-images.githubusercontent.com/13357430/34320377-688ade16-e83c-11e7-9059-990054a53dfc.PNG)

**Comment by mikuta0407** [comment]
未脱獄のiOS10にて同様の不具合を確認しました。

**Comment by ryotayama** [comment]
#274 停止ボタンを押した場合、コントロールセンターでハヤえもんにならないように修正してほしい。の対応にて、こちらの不具合も修正されている事を確認したので、closeします！
