### ISSUE TITLE
コントロールセンターでの再生終了判定がない? 

### ISSUE THREAD

**Issue by mikuta0407** [ryotayama/Hayaemon#95]
再生リストを通常モードで再生後、最後の曲が終わっても、コントロールセンターでは曲名こそでていないものの再生しているかのような表示になっている。(再生ボタンが)

~(iOS9かつ脱獄をしているため、他環境では再現性のない事象かもしれません。)~
![img_9096](https://user-images.githubusercontent.com/13357430/34320393-cc7df8ea-e83c-11e7-9708-b4b1d6b69d15.PNG)

**Comment by arigayas** [comment]
脱獄している機種までサポートするのは妥当なのか？って思う。

**Comment by mikuta0407** [comment]
未脱獄のiOS10にて同様の不具合を確認しました。

**Comment by ryotayama** [comment]
#274 停止ボタンを押した場合、コントロールセンターでハヤえもんにならないように修正してほしい。 の対応にて、こちらの不具合も修正されている事を確認したので、closeします！
