### ISSUE TITLE
イコライザープリセットを整理しようとすると落ちる

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon#98]
動画：https://twitter.com/kengo1228/status/946805977222754304
『#ハヤえもん　#エラー報告
イコライザープリセットを整理しようとすると落ちる。
これ前もあった気がするな。』

https://twitter.com/ryota_yama/status/946887839454674944
『これが再現できないんだよなぁ(*ノﾉ)』

**Comment by arigayas** [comment]
https://twitter.com/kengo1228/status/946983777363824641
『再生してない時も落ちます！』

**Comment by ryotayama** [comment]
#204 プリセットの項目を並べ替えようとするとアプリが強制終了してしまう と重複している為、こちらをcloseします。
